#pragma once

// Generated by tools/generate-steam-achievements.py. Do not edit.
//
// The retail achievement names defined on Steam application 224540.
// Steam refuses a name its schema does not know, so these are copied
// from the application's public achievement list rather than invented.

#include <array>
#include <string_view>

namespace battlespades::platform {

/** Every achievement the retail application defines (77). */
inline constexpr std::array<std::string_view, 77> retail_achievements{
    "airborne_for_hour",
    "airborne_rockets",
    "ammo_drop_greedy",
    "blocks_as_zombie",
    "bomb_final_bomber",
    "bomb_hotfoot",
    "bomb_interceptor",
    "bomb_survivor",
    "classic_kills_with_intel",
    "classic_rifle_headshots",
    "demolition_damage_many_rounds",
    "demolition_damage_one_round",
    "demolition_final_damage",
    "demolition_repair",
    "diamond_collector",
    "diamond_hotfoot",
    "diamond_interceptor",
    "diamond_thief",
    "drillgun_demolition",
    "dynamite_below",
    "grenade_demolish",
    "health_drop_greedy",
    "hill_defender",
    "hill_greedy",
    "hill_interceptor",
    "hill_kill_shooting_in",
    "hill_kill_shooting_out",
    "hill_strike_stay_put",
    "hill_strike_survivor",
    "intel_defence_easy",
    "intel_defence_hard",
    "jetpack_kill",
    "jetpack_killed_using",
    "jetpack_smg_kill",
    "knife_zombies",
    "landmine_hidden",
    "lastman_kills_zombies_easy",
    "lastman_kills_zombies_hard",
    "low_health_killing",
    "map_colosseum_kill",
    "map_concrete_destroy",
    "map_egypt_destroy",
    "map_greatwall_destroy",
    "map_isleofdoom_destroy",
    "map_london_destroy",
    "map_maya_kill",
    "map_moon_destroy",
    "map_zombieisland_destroy",
    "map_zombieisland_zombie_kill",
    "minigun_demolish",
    "misc_fifteen_in_a_row",
    "misc_five_in_a_row",
    "misc_half_marathon",
    "misc_marathon",
    "misc_ten_in_a_row",
    "misc_triple_explosion",
    "pickaxe_kill",
    "pistol_zombie_kill",
    "rocket_fall",
    "shotgun_headshots",
    "sniper2_rapid_kill",
    "sniper_accuracy",
    "sniper_accuracy_hard",
    "sniper_kill",
    "sniper_kill_hard",
    "spade_kill",
    "turret_accuracy",
    "turret_evasion",
    "vip_mvp",
    "vip_pacifist",
    "zombie_fall",
    "zombie_kills_humans",
    "zombie_kills_in_water_ach",
    "zombie_lms_multi_round",
    "zombie_lms_one_round",
    "zombie_mvp",
    "zombie_survivor",
};

/** True when Steam's schema for the retail application defines this name. */
[[nodiscard]] inline constexpr bool is_retail_achievement(std::string_view name) noexcept {
    for (const auto candidate : retail_achievements) {
        if (candidate == name) return true;
    }
    return false;
}

} // namespace battlespades::platform
