// Generated by tools/generate_class_catalog.py; do not edit.
#include "battlespades/world/class_catalog.hpp"

#include "battlespades/world/weapon_catalog.hpp"

#include <algorithm>
#include <array>

namespace battlespades::world {
namespace {

constexpr std::array<std::uint16_t, 2U> class_0_group_0{{2U, 1U}};
constexpr std::array<std::uint16_t, 2U> class_0_group_1{{8U, 60U}};
constexpr std::array<std::uint16_t, 2U> class_0_group_2{{12U, 13U}};
constexpr std::array<std::uint16_t, 3U> class_0_group_3{{11U, 32U, 72U}};
constexpr std::array<std::uint16_t, 3U> class_0_group_4{{0U, 8U, 7U}};
constexpr std::array<std::uint16_t, 7U> class_0_group_5{{5U, 23U, 22U, 30U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_0_group_6{{}};
constexpr std::array<std::string_view, 4U> class_0_prefabs{{std::string_view{"prefab_ultrabarrier"}, std::string_view{"prefab_superbarrier"}, std::string_view{"prefab_supersmallwall"}, std::string_view{"prefab_fort_wall"}}};

constexpr std::array<std::uint16_t, 2U> class_1_group_0{{0U, 1U}};
constexpr std::array<std::uint16_t, 2U> class_1_group_1{{18U, 19U}};
constexpr std::array<std::uint16_t, 2U> class_1_group_2{{17U, 53U}};
constexpr std::array<std::uint16_t, 2U> class_1_group_3{{20U, 56U}};
constexpr std::array<std::uint16_t, 3U> class_1_group_4{{1U, 8U, 7U}};
constexpr std::array<std::uint16_t, 7U> class_1_group_5{{5U, 23U, 22U, 30U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_1_group_6{{}};
constexpr std::array<std::string_view, 4U> class_1_prefabs{{std::string_view{"prefab_supertower"}, std::string_view{"prefab_superbridge"}, std::string_view{"prefab_superminibunker"}, std::string_view{"prefab_caltrop"}}};

constexpr std::array<std::uint16_t, 2U> class_2_group_0{{2U, 0U}};
constexpr std::array<std::uint16_t, 1U> class_2_group_1{{7U}};
constexpr std::array<std::uint16_t, 2U> class_2_group_2{{16U, 11U}};
constexpr std::array<std::uint16_t, 2U> class_2_group_3{{67U, 66U}};
constexpr std::array<std::uint16_t, 3U> class_2_group_4{{2U, 8U, 7U}};
constexpr std::array<std::uint16_t, 7U> class_2_group_5{{5U, 23U, 22U, 30U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_2_group_6{{}};
constexpr std::array<std::string_view, 3U> class_2_prefabs{{std::string_view{"prefab_caltrop"}, std::string_view{"prefab_superminibunker"}, std::string_view{"prefab_safety_tube"}}};

constexpr std::array<std::uint16_t, 1U> class_3_group_0{{3U}};
constexpr std::array<std::uint16_t, 2U> class_3_group_1{{9U, 10U}};
constexpr std::array<std::uint16_t, 2U> class_3_group_2{{14U, 63U}};
constexpr std::array<std::uint16_t, 2U> class_3_group_3{{21U, 59U}};
constexpr std::array<std::uint16_t, 3U> class_3_group_4{{3U, 8U, 7U}};
constexpr std::array<std::uint16_t, 7U> class_3_group_5{{5U, 23U, 22U, 30U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_3_group_6{{}};
constexpr std::array<std::string_view, 3U> class_3_prefabs{{std::string_view{"prefab_superdome"}, std::string_view{"prefab_superpole"}, std::string_view{"prefab_safety_corridor"}}};

constexpr std::array<std::uint16_t, 0U> class_4_group_0{{}};
constexpr std::array<std::uint16_t, 1U> class_4_group_1{{24U}};
constexpr std::array<std::uint16_t, 0U> class_4_group_2{{}};
constexpr std::array<std::uint16_t, 0U> class_4_group_3{{}};
constexpr std::array<std::uint16_t, 1U> class_4_group_4{{4U}};
constexpr std::array<std::uint16_t, 1U> class_4_group_5{{28U}};
constexpr std::array<std::uint16_t, 0U> class_4_group_6{{}};
constexpr std::array<std::string_view, 3U> class_4_prefabs{{std::string_view{"prefab_zombiehand"}, std::string_view{"prefab_zombiebone"}, std::string_view{"prefab_zombiehead"}}};

constexpr std::array<std::uint16_t, 1U> class_5_group_0{{4U}};
constexpr std::array<std::uint16_t, 3U> class_5_group_1{{6U, 38U, 37U}};
constexpr std::array<std::uint16_t, 0U> class_5_group_2{{}};
constexpr std::array<std::uint16_t, 1U> class_5_group_3{{31U}};
constexpr std::array<std::uint16_t, 0U> class_5_group_4{{}};
constexpr std::array<std::uint16_t, 4U> class_5_group_5{{5U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_5_group_6{{}};
constexpr std::array<std::string_view, 0U> class_5_prefabs{{}};

constexpr std::array<std::uint16_t, 1U> class_6_group_0{{34U}};
constexpr std::array<std::uint16_t, 1U> class_6_group_1{{35U}};
constexpr std::array<std::uint16_t, 1U> class_6_group_2{{36U}};
constexpr std::array<std::uint16_t, 1U> class_6_group_3{{33U}};
constexpr std::array<std::uint16_t, 3U> class_6_group_4{{6U, 8U, 7U}};
constexpr std::array<std::uint16_t, 7U> class_6_group_5{{5U, 23U, 22U, 30U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_6_group_6{{}};
constexpr std::array<std::string_view, 3U> class_6_prefabs{{std::string_view{"prefab_small_platform"}, std::string_view{"prefab_ladder"}, std::string_view{"prefab_square_bunker"}}};

constexpr std::array<std::uint16_t, 1U> class_7_group_0{{34U}};
constexpr std::array<std::uint16_t, 1U> class_7_group_1{{35U}};
constexpr std::array<std::uint16_t, 1U> class_7_group_2{{36U}};
constexpr std::array<std::uint16_t, 1U> class_7_group_3{{33U}};
constexpr std::array<std::uint16_t, 3U> class_7_group_4{{6U, 8U, 7U}};
constexpr std::array<std::uint16_t, 7U> class_7_group_5{{5U, 23U, 22U, 30U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_7_group_6{{}};
constexpr std::array<std::string_view, 3U> class_7_prefabs{{std::string_view{"prefab_small_platform"}, std::string_view{"prefab_ladder"}, std::string_view{"prefab_square_bunker"}}};

constexpr std::array<std::uint16_t, 1U> class_8_group_0{{34U}};
constexpr std::array<std::uint16_t, 1U> class_8_group_1{{35U}};
constexpr std::array<std::uint16_t, 1U> class_8_group_2{{36U}};
constexpr std::array<std::uint16_t, 1U> class_8_group_3{{33U}};
constexpr std::array<std::uint16_t, 3U> class_8_group_4{{6U, 8U, 7U}};
constexpr std::array<std::uint16_t, 7U> class_8_group_5{{5U, 23U, 22U, 30U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_8_group_6{{}};
constexpr std::array<std::string_view, 3U> class_8_prefabs{{std::string_view{"prefab_small_platform"}, std::string_view{"prefab_ladder"}, std::string_view{"prefab_square_bunker"}}};

constexpr std::array<std::uint16_t, 1U> class_9_group_0{{34U}};
constexpr std::array<std::uint16_t, 1U> class_9_group_1{{35U}};
constexpr std::array<std::uint16_t, 1U> class_9_group_2{{36U}};
constexpr std::array<std::uint16_t, 1U> class_9_group_3{{33U}};
constexpr std::array<std::uint16_t, 3U> class_9_group_4{{6U, 8U, 7U}};
constexpr std::array<std::uint16_t, 7U> class_9_group_5{{5U, 23U, 22U, 30U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_9_group_6{{}};
constexpr std::array<std::string_view, 3U> class_9_prefabs{{std::string_view{"prefab_small_platform"}, std::string_view{"prefab_ladder"}, std::string_view{"prefab_square_bunker"}}};

constexpr std::array<std::uint16_t, 1U> class_10_group_0{{34U}};
constexpr std::array<std::uint16_t, 1U> class_10_group_1{{35U}};
constexpr std::array<std::uint16_t, 1U> class_10_group_2{{36U}};
constexpr std::array<std::uint16_t, 1U> class_10_group_3{{33U}};
constexpr std::array<std::uint16_t, 3U> class_10_group_4{{6U, 8U, 7U}};
constexpr std::array<std::uint16_t, 7U> class_10_group_5{{5U, 23U, 22U, 30U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_10_group_6{{}};
constexpr std::array<std::string_view, 3U> class_10_prefabs{{std::string_view{"prefab_small_platform"}, std::string_view{"prefab_ladder"}, std::string_view{"prefab_square_bunker"}}};

constexpr std::array<std::uint16_t, 1U> class_11_group_0{{34U}};
constexpr std::array<std::uint16_t, 1U> class_11_group_1{{35U}};
constexpr std::array<std::uint16_t, 1U> class_11_group_2{{36U}};
constexpr std::array<std::uint16_t, 1U> class_11_group_3{{33U}};
constexpr std::array<std::uint16_t, 3U> class_11_group_4{{6U, 8U, 7U}};
constexpr std::array<std::uint16_t, 7U> class_11_group_5{{5U, 23U, 22U, 30U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_11_group_6{{}};
constexpr std::array<std::string_view, 3U> class_11_prefabs{{std::string_view{"prefab_small_platform"}, std::string_view{"prefab_ladder"}, std::string_view{"prefab_square_bunker"}}};

constexpr std::array<std::uint16_t, 1U> class_12_group_0{{0U}};
constexpr std::array<std::uint16_t, 1U> class_12_group_1{{7U}};
constexpr std::array<std::uint16_t, 3U> class_12_group_2{{16U, 29U, 58U}};
constexpr std::array<std::uint16_t, 2U> class_12_group_3{{68U, 64U}};
constexpr std::array<std::uint16_t, 3U> class_12_group_4{{9U, 8U, 7U}};
constexpr std::array<std::uint16_t, 7U> class_12_group_5{{5U, 23U, 22U, 30U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_12_group_6{{}};
constexpr std::array<std::string_view, 7U> class_12_prefabs{{std::string_view{"prefab_caltrop"}, std::string_view{"prefab_supertower"}, std::string_view{"prefab_ultrabarrier"}, std::string_view{"prefab_platform"}, std::string_view{"prefab_superminibunker"}, std::string_view{"prefab_superdome"}, std::string_view{"prefab_fort_wall"}}};

constexpr std::array<std::uint16_t, 1U> class_13_group_0{{45U}};
constexpr std::array<std::uint16_t, 1U> class_13_group_1{{47U}};
constexpr std::array<std::uint16_t, 1U> class_13_group_2{{48U}};
constexpr std::array<std::uint16_t, 1U> class_13_group_3{{69U}};
constexpr std::array<std::uint16_t, 3U> class_13_group_4{{10U, 8U, 7U}};
constexpr std::array<std::uint16_t, 9U> class_13_group_5{{5U, 43U, 22U, 30U, 42U, 41U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 1U> class_13_group_6{{0U}};
constexpr std::array<std::string_view, 0U> class_13_prefabs{{}};

constexpr std::array<std::uint16_t, 0U> class_14_group_0{{}};
constexpr std::array<std::uint16_t, 1U> class_14_group_1{{24U}};
constexpr std::array<std::uint16_t, 0U> class_14_group_2{{}};
constexpr std::array<std::uint16_t, 0U> class_14_group_3{{}};
constexpr std::array<std::uint16_t, 1U> class_14_group_4{{4U}};
constexpr std::array<std::uint16_t, 1U> class_14_group_5{{28U}};
constexpr std::array<std::uint16_t, 0U> class_14_group_6{{}};
constexpr std::array<std::string_view, 3U> class_14_prefabs{{std::string_view{"prefab_zombiehand"}, std::string_view{"prefab_zombiebone"}, std::string_view{"prefab_zombiehead"}}};

constexpr std::array<std::uint16_t, 0U> class_15_group_0{{}};
constexpr std::array<std::uint16_t, 1U> class_15_group_1{{24U}};
constexpr std::array<std::uint16_t, 0U> class_15_group_2{{}};
constexpr std::array<std::uint16_t, 0U> class_15_group_3{{}};
constexpr std::array<std::uint16_t, 1U> class_15_group_4{{4U}};
constexpr std::array<std::uint16_t, 1U> class_15_group_5{{28U}};
constexpr std::array<std::uint16_t, 0U> class_15_group_6{{}};
constexpr std::array<std::string_view, 3U> class_15_prefabs{{std::string_view{"prefab_zombiehand"}, std::string_view{"prefab_zombiebone"}, std::string_view{"prefab_zombiehead"}}};

constexpr std::array<std::uint16_t, 2U> class_16_group_0{{2U, 50U}};
constexpr std::array<std::uint16_t, 2U> class_16_group_1{{62U, 7U}};
constexpr std::array<std::uint16_t, 2U> class_16_group_2{{53U, 55U}};
constexpr std::array<std::uint16_t, 2U> class_16_group_3{{54U, 57U}};
constexpr std::array<std::uint16_t, 3U> class_16_group_4{{13U, 8U, 7U}};
constexpr std::array<std::uint16_t, 7U> class_16_group_5{{5U, 23U, 22U, 30U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_16_group_6{{}};
constexpr std::array<std::string_view, 4U> class_16_prefabs{{std::string_view{"prefab_caltrop"}, std::string_view{"prefab_superpole"}, std::string_view{"prefab_fort_wall"}, std::string_view{"prefab_safety_corridor"}}};

constexpr std::array<std::uint16_t, 2U> class_17_group_0{{0U, 49U}};
constexpr std::array<std::uint16_t, 2U> class_17_group_1{{61U, 10U}};
constexpr std::array<std::uint16_t, 1U> class_17_group_2{{52U}};
constexpr std::array<std::uint16_t, 1U> class_17_group_3{{51U}};
constexpr std::array<std::uint16_t, 3U> class_17_group_4{{14U, 8U, 7U}};
constexpr std::array<std::uint16_t, 7U> class_17_group_5{{5U, 23U, 22U, 30U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_17_group_6{{}};
constexpr std::array<std::string_view, 4U> class_17_prefabs{{std::string_view{"prefab_supersmallwall"}, std::string_view{"prefab_ultrabarrier"}, std::string_view{"prefab_fort_wall"}, std::string_view{"prefab_superbridge"}}};

constexpr std::array<ClassDefinition, retail_class_count> classes{{
    ClassDefinition{
        0U, "SOLDIER", "Soldier",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Soldier_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Soldier_Body.kv6", {-1.0F, 1.5F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Soldier_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Soldier_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_Soldier_Arms_Upper.kv6", "kv6/Character_Soldier_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_0_group_0}, std::span<const std::uint16_t>{class_0_group_1}, std::span<const std::uint16_t>{class_0_group_2}, std::span<const std::uint16_t>{class_0_group_3}, std::span<const std::uint16_t>{class_0_group_4}, std::span<const std::uint16_t>{class_0_group_5}, std::span<const std::uint16_t>{class_0_group_6}},
        200U, 1000U,
        {"png/ui/in_game_menus/select_class/soldier_character_team1.png", "png/ui/in_game_menus/select_class/soldier_character_team2.png"},
        {"png/ui/in_game_menus/select_class/soldier_icon_team1.png", "png/ui/in_game_menus/select_class/soldier_icon_team2.png"}, "", 1.0},
    ClassDefinition{
        1U, "SCOUT", "Scout",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Scout_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Scout_Body.kv6", {0.0F, 1.5F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Scout_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Scout_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_Scout_Arms_Upper.kv6", "kv6/Character_Scout_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_1_group_0}, std::span<const std::uint16_t>{class_1_group_1}, std::span<const std::uint16_t>{class_1_group_2}, std::span<const std::uint16_t>{class_1_group_3}, std::span<const std::uint16_t>{class_1_group_4}, std::span<const std::uint16_t>{class_1_group_5}, std::span<const std::uint16_t>{class_1_group_6}},
        400U, 1000U,
        {"png/ui/in_game_menus/select_class/scout_character_team1.png", "png/ui/in_game_menus/select_class/scout_character_team2.png"},
        {"png/ui/in_game_menus/select_class/scout_icon_team1.png", "png/ui/in_game_menus/select_class/scout_icon_team2.png"}, "", 1.43},
    ClassDefinition{
        2U, "ROCKETEER", "Rocketeer",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Rocketeer_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Rocketeer_Body.kv6", {0.0F, 0.0F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Rocketeer_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Rocketeer_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_Rocketeer_Arms_Upper.kv6", "kv6/Character_Rocketeer_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_2_group_0}, std::span<const std::uint16_t>{class_2_group_1}, std::span<const std::uint16_t>{class_2_group_2}, std::span<const std::uint16_t>{class_2_group_3}, std::span<const std::uint16_t>{class_2_group_4}, std::span<const std::uint16_t>{class_2_group_5}, std::span<const std::uint16_t>{class_2_group_6}},
        500U, 1500U,
        {"png/ui/in_game_menus/select_class/pilot_character_team1.png", "png/ui/in_game_menus/select_class/pilot_character_team2.png"},
        {"png/ui/in_game_menus/select_class/pilot_icon_team1.png", "png/ui/in_game_menus/select_class/pilot_icon_team2.png"}, "", 1.43},
    ClassDefinition{
        3U, "MINER", "Miner",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Miner_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Miner_Body.kv6", {0.0F, 0.0F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Miner_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Miner_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_Miner_Arms_Upper.kv6", "kv6/Character_Miner_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_3_group_0}, std::span<const std::uint16_t>{class_3_group_1}, std::span<const std::uint16_t>{class_3_group_2}, std::span<const std::uint16_t>{class_3_group_3}, std::span<const std::uint16_t>{class_3_group_4}, std::span<const std::uint16_t>{class_3_group_5}, std::span<const std::uint16_t>{class_3_group_6}},
        0U, 1000U,
        {"png/ui/in_game_menus/select_class/miner_character_team1.png", "png/ui/in_game_menus/select_class/miner_character_team2.png"},
        {"png/ui/in_game_menus/select_class/miner_icon_team1.png", "png/ui/in_game_menus/select_class/miner_icon_team2.png"}, "", 1.1765},
    ClassDefinition{
        4U, "ZOMBIE", "Zombie",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Zombie_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Zombie_Body.kv6", {0.0F, 0.0F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, 0.0F, 0.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Zombie_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Zombie_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"", ""},
        {std::span<const std::uint16_t>{class_4_group_0}, std::span<const std::uint16_t>{class_4_group_1}, std::span<const std::uint16_t>{class_4_group_2}, std::span<const std::uint16_t>{class_4_group_3}, std::span<const std::uint16_t>{class_4_group_4}, std::span<const std::uint16_t>{class_4_group_5}, std::span<const std::uint16_t>{class_4_group_6}},
        1000U, 2000U,
        {"png/ui/in_game_menus/select_class/zombie_character_team1.png", "png/ui/in_game_menus/select_class/zombie_character_team2.png"},
        {"png/ui/in_game_menus/select_class/zombie_icon.png", "png/ui/in_game_menus/select_class/zombie_icon.png"}, "", 0.6},
    ClassDefinition{
        5U, "CLASSIC_SOLDIER", "Classic Soldier",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Deuce_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Deuce_Body.kv6", {-1.0F, 1.5F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Deuce_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Deuce_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_Deuce_Arms_Upper.kv6", "kv6/Character_Deuce_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_5_group_0}, std::span<const std::uint16_t>{class_5_group_1}, std::span<const std::uint16_t>{class_5_group_2}, std::span<const std::uint16_t>{class_5_group_3}, std::span<const std::uint16_t>{class_5_group_4}, std::span<const std::uint16_t>{class_5_group_5}, std::span<const std::uint16_t>{class_5_group_6}},
        25U, 100U,
        {"png/ui/in_game_menus/select_class/classic_character_team1.png", "png/ui/in_game_menus/select_class/classic_character_team2.png"},
        {"png/ui/in_game_menus/select_class/classic_icon_team1.png", "png/ui/in_game_menus/select_class/classic_icon_team2.png"}, "", 1.0},
    ClassDefinition{
        6U, "GANGSTER_1", "Gangster 1",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Gangster1_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Gangster1_Body.kv6", {-1.0F, 1.5F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Gangster1_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Gangster1_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_Gangster1_Arms_Upper.kv6", "kv6/Character_Gangster1_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_6_group_0}, std::span<const std::uint16_t>{class_6_group_1}, std::span<const std::uint16_t>{class_6_group_2}, std::span<const std::uint16_t>{class_6_group_3}, std::span<const std::uint16_t>{class_6_group_4}, std::span<const std::uint16_t>{class_6_group_5}, std::span<const std::uint16_t>{class_6_group_6}},
        500U, 1200U,
        {"png/ui/in_game_menus/select_class/soldier_character_team1.png", "png/ui/in_game_menus/select_class/soldier_character_team2.png"},
        {"png/ui/in_game_menus/select_class/gangster1_icon_team1.png", "png/ui/in_game_menus/select_class/gangster1_icon_team2.png"}, "mafia", 1.0},
    ClassDefinition{
        7U, "GANGSTER_2", "Gangster 2",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Gangster2_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Gangster2_Body.kv6", {-1.0F, 1.5F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Gangster2_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Gangster2_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_Gangster2_Arms_Upper.kv6", "kv6/Character_Gangster2_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_7_group_0}, std::span<const std::uint16_t>{class_7_group_1}, std::span<const std::uint16_t>{class_7_group_2}, std::span<const std::uint16_t>{class_7_group_3}, std::span<const std::uint16_t>{class_7_group_4}, std::span<const std::uint16_t>{class_7_group_5}, std::span<const std::uint16_t>{class_7_group_6}},
        500U, 1200U,
        {"png/ui/in_game_menus/select_class/soldier_character_team1.png", "png/ui/in_game_menus/select_class/soldier_character_team2.png"},
        {"png/ui/in_game_menus/select_class/gangster2_icon_team1.png", "png/ui/in_game_menus/select_class/gangster2_icon_team2.png"}, "mafia", 1.0},
    ClassDefinition{
        8U, "GANGSTER_3", "Gangster 3",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Gangster3_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Gangster3_Body.kv6", {-1.0F, 1.5F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Gangster3_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Gangster3_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_Gangster3_Arms_Upper.kv6", "kv6/Character_Gangster3_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_8_group_0}, std::span<const std::uint16_t>{class_8_group_1}, std::span<const std::uint16_t>{class_8_group_2}, std::span<const std::uint16_t>{class_8_group_3}, std::span<const std::uint16_t>{class_8_group_4}, std::span<const std::uint16_t>{class_8_group_5}, std::span<const std::uint16_t>{class_8_group_6}},
        500U, 1200U,
        {"png/ui/in_game_menus/select_class/soldier_character_team1.png", "png/ui/in_game_menus/select_class/soldier_character_team2.png"},
        {"png/ui/in_game_menus/select_class/gangster3_icon_team1.png", "png/ui/in_game_menus/select_class/gangster3_icon_team2.png"}, "mafia", 1.0},
    ClassDefinition{
        9U, "GANGSTER_4", "Gangster 4",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Gangster4_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Gangster4_Body.kv6", {-1.0F, 1.5F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Gangster4_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Gangster4_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_Gangster4_Arms_Upper.kv6", "kv6/Character_Gangster4_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_9_group_0}, std::span<const std::uint16_t>{class_9_group_1}, std::span<const std::uint16_t>{class_9_group_2}, std::span<const std::uint16_t>{class_9_group_3}, std::span<const std::uint16_t>{class_9_group_4}, std::span<const std::uint16_t>{class_9_group_5}, std::span<const std::uint16_t>{class_9_group_6}},
        500U, 1200U,
        {"png/ui/in_game_menus/select_class/soldier_character_team1.png", "png/ui/in_game_menus/select_class/soldier_character_team2.png"},
        {"png/ui/in_game_menus/select_class/gangster4_icon_team1.png", "png/ui/in_game_menus/select_class/gangster4_icon_team2.png"}, "mafia", 1.0},
    ClassDefinition{
        10U, "GANGSTER_VIP_1", "Gangster VIP 1",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_GangsterVIP1_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_GangsterVIP1_Body.kv6", {-1.0F, 1.5F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_GangsterVIP1_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_GangsterVIP1_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_GangsterVIP1_Arms_Upper.kv6", "kv6/Character_GangsterVIP1_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_10_group_0}, std::span<const std::uint16_t>{class_10_group_1}, std::span<const std::uint16_t>{class_10_group_2}, std::span<const std::uint16_t>{class_10_group_3}, std::span<const std::uint16_t>{class_10_group_4}, std::span<const std::uint16_t>{class_10_group_5}, std::span<const std::uint16_t>{class_10_group_6}},
        500U, 1200U,
        {"png/ui/in_game_menus/select_class/soldier_character_team1.png", "png/ui/in_game_menus/select_class/soldier_character_team2.png"},
        {"png/ui/in_game_menus/select_class/boss_icon_team1.png", "png/ui/in_game_menus/select_class/boss_icon_team2.png"}, "mafia", 1.0},
    ClassDefinition{
        11U, "GANGSTER_VIP_2", "Gangster VIP 2",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_GangsterVIP2_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_GangsterVIP2_Body.kv6", {-1.0F, 1.5F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_GangsterVIP2_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_GangsterVIP2_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_GangsterVIP2_Arms_Upper.kv6", "kv6/Character_GangsterVIP2_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_11_group_0}, std::span<const std::uint16_t>{class_11_group_1}, std::span<const std::uint16_t>{class_11_group_2}, std::span<const std::uint16_t>{class_11_group_3}, std::span<const std::uint16_t>{class_11_group_4}, std::span<const std::uint16_t>{class_11_group_5}, std::span<const std::uint16_t>{class_11_group_6}},
        500U, 1200U,
        {"png/ui/in_game_menus/select_class/soldier_character_team1.png", "png/ui/in_game_menus/select_class/soldier_character_team2.png"},
        {"png/ui/in_game_menus/select_class/boss_icon_team1.png", "png/ui/in_game_menus/select_class/boss_icon_team2.png"}, "mafia", 1.0},
    ClassDefinition{
        12U, "ENGINEER", "Engineer",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Engineer_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Engineer_Body.kv6", {0.0F, 0.0F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Engineer_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Engineer_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_Engineer_Arms_Upper.kv6", "kv6/Character_Engineer_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_12_group_0}, std::span<const std::uint16_t>{class_12_group_1}, std::span<const std::uint16_t>{class_12_group_2}, std::span<const std::uint16_t>{class_12_group_3}, std::span<const std::uint16_t>{class_12_group_4}, std::span<const std::uint16_t>{class_12_group_5}, std::span<const std::uint16_t>{class_12_group_6}},
        2000U, 3000U,
        {"png/ui/in_game_menus/select_class/engineer_character_team1.png", "png/ui/in_game_menus/select_class/engineer_character_team2.png"},
        {"png/ui/in_game_menus/select_class/engineer_icon_team1.png", "png/ui/in_game_menus/select_class/engineer_icon_team2.png"}, "", 1.1765},
    ClassDefinition{
        13U, "UGCBUILDER", "UGC Builder",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_UGCBuilder_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_UGCBuilder_Body.kv6", {0.0F, 0.0F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_UGCBuilder_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_UGCBuilder_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_UGCBuilder_Arms_Upper.kv6", "kv6/Character_UGCBuilder_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_13_group_0}, std::span<const std::uint16_t>{class_13_group_1}, std::span<const std::uint16_t>{class_13_group_2}, std::span<const std::uint16_t>{class_13_group_3}, std::span<const std::uint16_t>{class_13_group_4}, std::span<const std::uint16_t>{class_13_group_5}, std::span<const std::uint16_t>{class_13_group_6}},
        1U, 1U,
        {"png/ui/in_game_menus/select_class/ugcbuilder_character_team1.png", "png/ui/in_game_menus/select_class/ugcbuilder_character_team2.png"},
        {"png/ui/in_game_menus/select_class/ugcbuilder_icon_team1.png", "png/ui/in_game_menus/select_class/ugcbuilder_icon_team2.png"}, "", 0.0},
    ClassDefinition{
        14U, "FAST_ZOMBIE", "Fast Zombie",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Zombie_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Zombie_Body.kv6", {0.0F, 0.0F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, 0.0F, 0.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Zombie_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Zombie_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"", ""},
        {std::span<const std::uint16_t>{class_14_group_0}, std::span<const std::uint16_t>{class_14_group_1}, std::span<const std::uint16_t>{class_14_group_2}, std::span<const std::uint16_t>{class_14_group_3}, std::span<const std::uint16_t>{class_14_group_4}, std::span<const std::uint16_t>{class_14_group_5}, std::span<const std::uint16_t>{class_14_group_6}},
        500U, 1000U,
        {"png/ui/in_game_menus/select_class/zombie_character_team1.png", "png/ui/in_game_menus/select_class/zombie_character_team2.png"},
        {"png/ui/in_game_menus/select_class/zombie_icon.png", "png/ui/in_game_menus/select_class/zombie_icon.png"}, "", 0.5},
    ClassDefinition{
        15U, "JUMP_ZOMBIE", "Jump Zombie",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Zombie_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Zombie_Body.kv6", {0.0F, 0.0F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, 0.0F, 0.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Zombie_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Zombie_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"", ""},
        {std::span<const std::uint16_t>{class_15_group_0}, std::span<const std::uint16_t>{class_15_group_1}, std::span<const std::uint16_t>{class_15_group_2}, std::span<const std::uint16_t>{class_15_group_3}, std::span<const std::uint16_t>{class_15_group_4}, std::span<const std::uint16_t>{class_15_group_5}, std::span<const std::uint16_t>{class_15_group_6}},
        500U, 1000U,
        {"png/ui/in_game_menus/select_class/zombie_character_team1.png", "png/ui/in_game_menus/select_class/zombie_character_team2.png"},
        {"png/ui/in_game_menus/select_class/zombie_icon.png", "png/ui/in_game_menus/select_class/zombie_icon.png"}, "", 0.5},
    ClassDefinition{
        16U, "SPECIALIST", "Specialist",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Specialist_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Specialist_Body.kv6", {0.0F, 1.5F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Specialist_Leg_L.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Specialist_Leg_R.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_Specialist_Arms_Upper.kv6", "kv6/Character_Specialist_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_16_group_0}, std::span<const std::uint16_t>{class_16_group_1}, std::span<const std::uint16_t>{class_16_group_2}, std::span<const std::uint16_t>{class_16_group_3}, std::span<const std::uint16_t>{class_16_group_4}, std::span<const std::uint16_t>{class_16_group_5}, std::span<const std::uint16_t>{class_16_group_6}},
        400U, 1000U,
        {"png/ui/in_game_menus/select_class/specialist_character_team1.png", "png/ui/in_game_menus/select_class/specialist_character_team2.png"},
        {"png/ui/in_game_menus/select_class/specialist_icon_team1.png", "png/ui/in_game_menus/select_class/specialist_icon_team2.png"}, "", 1.1765},
    ClassDefinition{
        17U, "MEDIC", "Medic",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Medic_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Medic_Body.kv6", {-1.0F, 1.5F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Medic_Leg_L.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Medic_Leg_R.kv6", {-2.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_Medic_Arms_Upper.kv6", "kv6/Character_Medic_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_17_group_0}, std::span<const std::uint16_t>{class_17_group_1}, std::span<const std::uint16_t>{class_17_group_2}, std::span<const std::uint16_t>{class_17_group_3}, std::span<const std::uint16_t>{class_17_group_4}, std::span<const std::uint16_t>{class_17_group_5}, std::span<const std::uint16_t>{class_17_group_6}},
        900U, 2000U,
        {"png/ui/in_game_menus/select_class/medic_character_team1.png", "png/ui/in_game_menus/select_class/medic_character_team2.png"},
        {"png/ui/in_game_menus/select_class/medic_icon_team1.png", "png/ui/in_game_menus/select_class/medic_icon_team2.png"}, "", 1.0},
}};

constexpr std::array<std::span<const std::string_view>, retail_class_count> prefab_names{{
    std::span<const std::string_view>{class_0_prefabs},
    std::span<const std::string_view>{class_1_prefabs},
    std::span<const std::string_view>{class_2_prefabs},
    std::span<const std::string_view>{class_3_prefabs},
    std::span<const std::string_view>{class_4_prefabs},
    std::span<const std::string_view>{class_5_prefabs},
    std::span<const std::string_view>{class_6_prefabs},
    std::span<const std::string_view>{class_7_prefabs},
    std::span<const std::string_view>{class_8_prefabs},
    std::span<const std::string_view>{class_9_prefabs},
    std::span<const std::string_view>{class_10_prefabs},
    std::span<const std::string_view>{class_11_prefabs},
    std::span<const std::string_view>{class_12_prefabs},
    std::span<const std::string_view>{class_13_prefabs},
    std::span<const std::string_view>{class_14_prefabs},
    std::span<const std::string_view>{class_15_prefabs},
    std::span<const std::string_view>{class_16_prefabs},
    std::span<const std::string_view>{class_17_prefabs},
}};

constexpr std::array<std::string_view, retail_class_count> class_names{{std::string_view{"SOLDIER"}, std::string_view{"SCOUT"}, std::string_view{"ENGINEER"}, std::string_view{"MINER"}, std::string_view{"ZOMBIE"}, std::string_view{"CLASSIC_SOLDIER"}, std::string_view{"GANGSTER_1_NAME"}, std::string_view{"GANGSTER_2_NAME"}, std::string_view{"GANGSTER_3_NAME"}, std::string_view{"GANGSTER_4_NAME"}, std::string_view{"GANGSTER_VIP_1_NAME"}, std::string_view{"GANGSTER_VIP_2_NAME"}, std::string_view{"ENGINEER2"}, std::string_view{"UGCBUILDER"}, std::string_view{"FAST_ZOMBIE"}, std::string_view{"JUMP_ZOMBIE"}, std::string_view{"SPECIALIST"}, std::string_view{"MEDIC"}}};
constexpr std::array<std::string_view, retail_class_count> class_descriptions{{std::string_view{"SOLDIER_DESCRIPTION"}, std::string_view{"SCOUT_DESCRIPTION"}, std::string_view{"ROCKETEER_DESCRIPTION"}, std::string_view{"MINER_DESCRIPTION"}, std::string_view{"ZOMBIE_DESCRIPTION"}, std::string_view{"SOLDIER_DESCRIPTION"}, std::string_view{"GANGSTER_DESCRIPTION"}, std::string_view{"GANGSTER_DESCRIPTION"}, std::string_view{"GANGSTER_DESCRIPTION"}, std::string_view{"GANGSTER_DESCRIPTION"}, std::string_view{"GANGSTER_DESCRIPTION"}, std::string_view{"GANGSTER_DESCRIPTION"}, std::string_view{"ENGINEER_DESCRIPTION"}, std::string_view{"UGCBUILDER_DESCRIPTION"}, std::string_view{"ZOMBIE_DESCRIPTION"}, std::string_view{"ZOMBIE_DESCRIPTION"}, std::string_view{"SPECIALIST_DESCRIPTION"}, std::string_view{"MEDIC_DESCRIPTION"}}};

constexpr std::string_view tool_name_key_for(std::uint16_t tool) noexcept {
    switch (tool) {
    case 0U: return "PICKAXE";
    case 1U: return "KNIFE";
    case 2U: return "SPADE";
    case 3U: return "SUPER_SPADE";
    case 4U: return "SPADE";
    case 5U: return "A301";
    case 6U: return "RIFLE";
    case 7U: return "SUB_MACHINE_GUN";
    case 8U: return "MINIGUN";
    case 9U: return "SHOTGUN";
    case 10U: return "SHOTGUN2";
    case 11U: return "A307";
    case 12U: return "ROCKET_PROPELLED_GRENADE";
    case 13U: return "ROCKET_PROPELLED_GRENADE2";
    case 14U: return "DRILL_TOOL";
    case 15U: return "MOUNTED_GUN";
    case 16U: return "ROCKET_TURRET";
    case 17U: return "PISTOL";
    case 18U: return "SNIPER_RIFLE";
    case 19U: return "SNIPER2_RIFLE";
    case 20U: return "A316";
    case 21U: return "A317";
    case 22U: return "FLARE_BLOCK_TOOL";
    case 23U: return "A319";
    case 24U: return "ZOMBIE_HANDS";
    case 25U: return "A321";
    case 26U: return "A322";
    case 27U: return "A323";
    case 28U: return "ZOMBIE_PREFAB_TOOL";
    case 29U: return "SNOWBLOWER";
    case 30U: return "A326";
    case 31U: return "CLASSIC_GRENADE";
    case 32U: return "A328";
    case 33U: return "A329";
    case 35U: return "A331";
    case 36U: return "A332";
    case 37U: return "CLASSIC_SHOTGUN";
    case 38U: return "CLASSIC_SUB_MACHINE_GUN";
    case 39U: return "NULL_TOOL";
    case 40U: return "FAKE_PISTOL_TOOL";
    case 41U: return "A337";
    case 42U: return "UGC_PREFAB_TOOL";
    case 43U: return "PAINTBRUSH_TOOL";
    case 44U: return "UGC_PICKAXE";
    case 45U: return "UGC_SUPERSPADE";
    case 46U: return "UGC_RPG2";
    case 47U: return "DRILL_TOOL";
    case 48U: return "SNOWBLOWER";
    case 49U: return "RIOTSTICK";
    case 50U: return "MACHETE";
    case 51U: return "MEDPACK_WEAPON";
    case 52U: return "RIOTSHIELD";
    case 53U: return "AUTOMATIC_PISTOL";
    case 54U: return "CHEMICALBOMB";
    case 55U: return "GRENADE_LAUNCHER_WEAPON";
    case 56U: return "RADAR_STATION";
    case 57U: return "STICKY_GRENADE";
    case 58U: return "MINE_LAUNCHER";
    case 59U: return "C4";
    case 60U: return "ASSAULT_RIFLE";
    case 61U: return "LIGHT_MACHINE_GUN";
    case 62U: return "AUTO_SHOTGUN";
    case 63U: return "BLOCK_SUCKER";
    case 64U: return "DISGUISE";
    case 66U: return "A364";
    case 67U: return "JETPACK_2";
    case 68U: return "A366";
    case 69U: return "A367";
    case 72U: return "A370";
    default: return {};
    }
}

constexpr std::string_view tool_description_key_for(std::uint16_t tool) noexcept {
    switch (tool) {
    case 0U: return "PICKAXE_TOOL_DESCRIPTION";
    case 1U: return "KNIFE_TOOL_DESCRIPTION";
    case 2U: return "SPADE_TOOL_DESCRIPTION";
    case 3U: return "SUPERSPADE_TOOL_DESCRIPTION";
    case 4U: return "CLASSIC_SPADE_TOOL_DESCRIPTION";
    case 6U: return "RIFLE_TOOL_DESCRIPTION";
    case 7U: return "SMG_TOOL_DESCRIPTION";
    case 8U: return "MINIGUN_TOOL_DESCRIPTION";
    case 9U: return "SHOTGUN_TOOL_DESCRIPTION";
    case 10U: return "SHOTGUN2_TOOL_DESCRIPTION";
    case 11U: return "GRENADE_TOOL_DESCRIPTION";
    case 12U: return "RPG_TOOL_DESCRIPTION";
    case 13U: return "RPG2_TOOL_DESCRIPTION";
    case 14U: return "DRILLGUN_TOOL_DESCRIPTION";
    case 15U: return "MG_TOOL_DESCRIPTION";
    case 16U: return "ROCKET_TURRET_TOOL_DESCRIPTION";
    case 17U: return "PISTOL_TOOL_DESCRIPTION";
    case 18U: return "SNIPER_TOOL_DESCRIPTION";
    case 19U: return "SNIPER2_TOOL_DESCRIPTION";
    case 20U: return "LANDMINE_TOOL_DESCRIPTION";
    case 21U: return "DYNAMITE_TOOL_DESCRIPTION";
    case 24U: return "ZOMBIEHAND_TOOL_DESCRIPTION";
    case 29U: return "SNOWBLOWER_DESCRIPTION";
    case 31U: return "CLASSIC_GRENADE_TOOL_DESCRIPTION";
    case 32U: return "ANTIPERSONNEL_GRENADE_TOOL_DESCRIPTION";
    case 33U: return "MOLOTOV_TOOL_DESCRIPTION";
    case 34U: return "CROWBAR_TOOL_DESCRIPTION";
    case 35U: return "TOMMYGUN_TOOL_DESCRIPTION";
    case 36U: return "SNUB_PISTOL_TOOL_DESCRIPTION";
    case 37U: return "CLASSIC_SHOTGUN_TOOL_DESCRIPTION";
    case 38U: return "CLASSIC_SMG_TOOL_DESCRIPTION";
    case 39U: return "NULL_TOOL_DESCRIPTION";
    case 40U: return "FAKE_PISTOL_TOOL_DESCRIPTION";
    case 41U: return "UGC_TOOL_DESCRIPTION";
    case 43U: return "PAINTBRUSH_TOOL_DESCRIPTION";
    case 44U: return "UGC_PICKAXE_TOOL_DESCRIPTION";
    case 45U: return "UGC_SUPERSPADE_TOOL_DESCRIPTION";
    case 46U: return "UGC_RPG2_TOOL_DESCRIPTION";
    case 47U: return "DRILLGUN_TOOL_DESCRIPTION";
    case 48U: return "SNOWBLOWER_DESCRIPTION";
    case 49U: return "RIOTSTICK_TOOL_DESCRIPTION";
    case 50U: return "MACHETE_TOOL_DESCRIPTION";
    case 51U: return "MEDPACK_TOOL_DESCRIPTION";
    case 52U: return "RIOTSHIELD_TOOL_DESCRIPTION";
    case 53U: return "AUTOPISTOL_TOOL_DESCRIPTION";
    case 54U: return "CHEMICALBOMB_TOOL_DESCRIPTION";
    case 55U: return "GRENADE_LAUNCHER_TOOL_DESCRIPTION";
    case 56U: return "RADAR_STATION_TOOL_DESCRIPTION";
    case 57U: return "STICKY_GRENADE_TOOL_DESCRIPTION";
    case 58U: return "MINE_LAUNCHER_TOOL_DESCRIPTION";
    case 59U: return "C4_TOOL_DESCRIPTION";
    case 60U: return "ASSAULTRIFLE_TOOL_DESCRIPTION";
    case 61U: return "LIGHTMACHINEGUN_TOOL_DESCRIPTION";
    case 62U: return "AUTOSHOTGUN_TOOL_DESCRIPTION";
    case 63U: return "BLOCKSUCKER_TOOL_DESCRIPTION";
    case 64U: return "DISGUISE_TOOL_DESCRIPTION";
    case 66U: return "JETPACK_NORMAL_DESCRIPTION";
    case 67U: return "JETPACK_2_DESCRIPTION";
    case 68U: return "JETPACK_ENGINEER_DESCRIPTION";
    case 69U: return "JETPACK_UGCBUILDER_DESCRIPTION";
    case 72U: return "PARACHUTE_NORMAL_DESCRIPTION";
    default: return {};
    }
}

constexpr std::array<UiSkinDefinition, 2U> skins{{
    UiSkinDefinition{"default", ""},
    UiSkinDefinition{"mafia", "skins/mafia/"},
}};

} // namespace

std::span<const ClassDefinition> class_catalog() noexcept { return classes; }

const ClassDefinition* find_class_definition(std::uint8_t class_id) noexcept {
    return class_id < classes.size() ? &classes[class_id] : nullptr;
}

std::span<const UiSkinDefinition> ui_skin_catalog() noexcept { return skins; }

const UiSkinDefinition* find_ui_skin(std::string_view id) noexcept {
    const auto found = std::ranges::find_if(skins, [id](const auto& skin) { return skin.id == id; });
    return found == skins.end() ? nullptr : &*found;
}

std::vector<std::uint16_t> default_class_items(const ClassDefinition& definition, bool include_flare, bool include_prefab_tool) {
    std::vector<std::uint16_t> result;
    for (std::size_t group{}; group < static_cast<std::size_t>(ClassItemGroup::common); ++group) {
        if (group == static_cast<std::size_t>(ClassItemGroup::prefab_sets) || definition.item_groups[group].empty()) continue;
        result.push_back(definition.item_groups[group].front());
    }
    for (const auto item : definition.item_groups[static_cast<std::size_t>(ClassItemGroup::common)]) {
        if (item == 22U && !include_flare) continue;
        if (item == 23U && !include_prefab_tool) continue;
        if (item == 5U) result.insert(result.begin(), item); else result.push_back(item);
    }
    if (definition.class_id != 4U && definition.class_id != 5U && definition.class_id != 14U && definition.class_id != 15U) {
        if (include_flare && std::ranges::find(result, 22U) == result.end()) result.push_back(22U);
        if (include_prefab_tool && std::ranges::find(result, 23U) == result.end()) result.push_back(23U);
    }
    return result;
}

std::vector<std::uint8_t> class_test_tools(const ClassDefinition& definition) {
    std::vector<std::uint8_t> result;
    for (std::size_t group{}; group < definition.item_groups.size(); ++group) {
        if (group == static_cast<std::size_t>(ClassItemGroup::prefab_sets) || group == static_cast<std::size_t>(ClassItemGroup::ugc_tools)) continue;
        for (const auto item : definition.item_groups[group]) {
            if (item <= 64U && valid_selectable_tool(static_cast<std::uint8_t>(item)) && std::ranges::find(result, static_cast<std::uint8_t>(item)) == result.end()) result.push_back(static_cast<std::uint8_t>(item));
        }
    }
    return result;
}

std::optional<std::uint8_t> preferred_spawn_tool(const ClassDefinition& definition, std::span<const std::uint8_t> loadout) noexcept {
    const auto primary = definition.item_groups[static_cast<std::size_t>(ClassItemGroup::primary)];
    for (const auto choice : primary) {
        if (choice <= 64U && valid_selectable_tool(static_cast<std::uint8_t>(choice)) && std::ranges::find(loadout, static_cast<std::uint8_t>(choice)) != loadout.end()) return static_cast<std::uint8_t>(choice);
    }
    const auto fallback = std::ranges::find_if(loadout, [](std::uint8_t tool) { return valid_selectable_tool(tool); });
    return fallback == loadout.end() ? std::nullopt : std::optional<std::uint8_t>{*fallback};
}

std::string_view class_item_group_name(ClassItemGroup group) noexcept {
    constexpr std::array names{std::string_view{"Melee"}, std::string_view{"Primary"}, std::string_view{"Secondary"}, std::string_view{"Equipment"}, std::string_view{"Prefab sets"}, std::string_view{"Common"}, std::string_view{"UGC tools"}};
    const auto index = static_cast<std::size_t>(group); return index < names.size() ? names[index] : std::string_view{};
}

std::string_view class_catalog_contract_sha256() noexcept { return "2e6b9f8f0955ea0db37ff29d735e07aae5bb233869645aaa6c6d946f43d3d22d"; }

std::span<const std::string_view> class_prefab_names(std::uint8_t class_id) noexcept {
    return class_id < prefab_names.size() ? prefab_names[class_id] : std::span<const std::string_view>{};
}

std::string_view class_name_key(std::uint8_t class_id) noexcept {
    return class_id < class_names.size() ? class_names[class_id] : std::string_view{};
}

std::string_view class_description_key(std::uint8_t class_id) noexcept {
    return class_id < class_descriptions.size() ? class_descriptions[class_id] : std::string_view{};
}

std::string_view tool_name_key(std::uint16_t tool) noexcept { return tool_name_key_for(tool); }

std::string_view tool_description_key(std::uint16_t tool) noexcept { return tool_description_key_for(tool); }

} // namespace battlespades::world
