// GENERATED by tools/generate_class_voice.py. Do not edit.
//
// Per-class voice-over banks recovered from the retail CLASS_SOUNDS table.
// An empty bank is a DELIBERATE silence, not a gap: several classes have no
// spawn line, and one has no death voice at all.
#include "battlespades/world/class_voice.hpp"

namespace battlespades::world {
namespace {

constexpr std::string_view c0_death_sound[]{"sol_death_vo_001", "sol_death_vo_002", "sol_death_vo_003", "sol_death_vo_004", "sol_death_vo_005", "sol_death_vo_006", "sol_death_vo_007", "sol_death_vo_008"};
constexpr std::string_view c0_spawn_vo[]{"sol_spawn_vo_001", "sol_spawn_vo_002", "sol_spawn_vo_003", "sol_spawn_vo_004", "sol_spawn_vo_005", "sol_spawn_vo_006"};
constexpr std::string_view c0_jump_vo[]{"sol_jump_vo_001", "sol_jump_vo_002", "sol_jump_vo_003", "sol_jump_vo_004", "sol_jump_vo_005", "sol_jump_vo_006", "sol_jump_vo_007", "sol_jump_vo_008"};
constexpr std::string_view c0_water_jump_vo[]{"sol_water_jump_vo_001", "sol_water_jump_vo_002", "sol_water_jump_vo_003", "sol_water_jump_vo_004", "sol_water_jump_vo_005", "sol_water_jump_vo_006", "sol_water_jump_vo_007", "sol_water_jump_vo_008"};
constexpr std::string_view c0_land_vo[]{"sol_land_vo_001", "sol_land_vo_002", "sol_land_vo_003", "sol_land_vo_004", "sol_land_vo_005", "sol_land_vo_006", "sol_land_vo_007", "sol_land_vo_008"};
constexpr std::string_view c0_water_land_vo[]{"sol_water_land_vo_001", "sol_water_land_vo_002", "sol_water_land_vo_003", "sol_water_land_vo_004", "sol_water_land_vo_005", "sol_water_land_vo_006", "sol_water_land_vo_007", "sol_water_land_vo_008"};
constexpr std::string_view c0_fall_hurt_vo[]{"sol_water_land_vo_001", "sol_water_land_vo_002", "sol_water_land_vo_003", "sol_water_land_vo_004", "sol_water_land_vo_005", "sol_water_land_vo_006", "sol_water_land_vo_007", "sol_water_land_vo_008"};
constexpr std::string_view c1_death_sound[]{"sco_death_vo_001", "sco_death_vo_002", "sco_death_vo_003", "sco_death_vo_004", "sco_death_vo_005", "sco_death_vo_006", "sco_death_vo_007", "sco_death_vo_008"};
constexpr std::string_view c1_spawn_vo[]{"sco_spawn_vo_001", "sco_spawn_vo_002", "sco_spawn_vo_003", "sco_spawn_vo_004", "sco_spawn_vo_005", "sco_spawn_vo_006"};
constexpr std::string_view c1_jump_vo[]{"sco_jump_vo_001", "sco_jump_vo_002", "sco_jump_vo_003", "sco_jump_vo_004", "sco_jump_vo_005", "sco_jump_vo_006", "sco_jump_vo_007", "sco_jump_vo_008"};
constexpr std::string_view c1_water_jump_vo[]{"sco_water_jump_vo_001", "sco_water_jump_vo_002", "sco_water_jump_vo_003", "sco_water_jump_vo_004", "sco_water_jump_vo_005", "sco_water_jump_vo_006", "sco_water_jump_vo_007", "sco_water_jump_vo_008"};
constexpr std::string_view c1_land_vo[]{"sco_land_vo_001", "sco_land_vo_002", "sco_land_vo_003", "sco_land_vo_004", "sco_land_vo_005", "sco_land_vo_006", "sco_land_vo_007", "sco_land_vo_008"};
constexpr std::string_view c1_water_land_vo[]{"sco_water_land_vo_001", "sco_water_land_vo_002", "sco_water_land_vo_003", "sco_water_land_vo_004", "sco_water_land_vo_005", "sco_water_land_vo_006", "sco_water_land_vo_007", "sco_water_land_vo_008"};
constexpr std::string_view c1_fall_hurt_vo[]{"sco_water_land_vo_001", "sco_water_land_vo_002", "sco_water_land_vo_003", "sco_water_land_vo_004", "sco_water_land_vo_005", "sco_water_land_vo_006", "sco_water_land_vo_007", "sco_water_land_vo_008"};
constexpr std::string_view c2_death_sound[]{"roc_death_vo_001", "roc_death_vo_002", "roc_death_vo_003", "roc_death_vo_004", "roc_death_vo_005", "roc_death_vo_006", "roc_death_vo_007", "roc_death_vo_008"};
constexpr std::string_view c2_spawn_vo[]{"roc_spawn_vo_001", "roc_spawn_vo_002", "roc_spawn_vo_003", "roc_spawn_vo_004", "roc_spawn_vo_005"};
constexpr std::string_view c2_jump_vo[]{"roc_jump_vo_001", "roc_jump_vo_002", "roc_jump_vo_003", "roc_jump_vo_004", "roc_jump_vo_005", "roc_jump_vo_006", "roc_jump_vo_007", "roc_jump_vo_008"};
constexpr std::string_view c2_water_jump_vo[]{"roc_water_jump_vo_001", "roc_water_jump_vo_002", "roc_water_jump_vo_003", "roc_water_jump_vo_004", "roc_water_jump_vo_005", "roc_water_jump_vo_006", "roc_water_jump_vo_007", "roc_water_jump_vo_008"};
constexpr std::string_view c2_land_vo[]{"roc_land_vo_001", "roc_land_vo_002", "roc_land_vo_003", "roc_land_vo_004", "roc_land_vo_005", "roc_land_vo_006", "roc_land_vo_007", "roc_land_vo_008"};
constexpr std::string_view c2_water_land_vo[]{"roc_water_land_vo_001", "roc_water_land_vo_002", "roc_water_land_vo_003", "roc_water_land_vo_004", "roc_water_land_vo_005", "roc_water_land_vo_006", "roc_water_land_vo_007", "roc_water_land_vo_008"};
constexpr std::string_view c2_fall_hurt_vo[]{"roc_water_land_vo_001", "roc_water_land_vo_002", "roc_water_land_vo_003", "roc_water_land_vo_004", "roc_water_land_vo_005", "roc_water_land_vo_006", "roc_water_land_vo_007", "roc_water_land_vo_008"};
constexpr std::string_view c3_death_sound[]{"min_death_vo_001", "min_death_vo_002", "min_death_vo_003", "min_death_vo_004", "min_death_vo_005", "min_death_vo_006", "min_death_vo_007", "min_death_vo_008"};
constexpr std::string_view c3_spawn_vo[]{"min_spawn_vo_001", "min_spawn_vo_002", "min_spawn_vo_003", "min_spawn_vo_004"};
constexpr std::string_view c3_jump_vo[]{"min_jump_vo_001", "min_jump_vo_002", "min_jump_vo_003", "min_jump_vo_004", "min_jump_vo_005", "min_jump_vo_006", "min_jump_vo_007", "min_jump_vo_008"};
constexpr std::string_view c3_water_jump_vo[]{"min_water_jump_vo_001", "min_water_jump_vo_002", "min_water_jump_vo_003", "min_water_jump_vo_004", "min_water_jump_vo_005", "min_water_jump_vo_006", "min_water_jump_vo_007", "min_water_jump_vo_008"};
constexpr std::string_view c3_land_vo[]{"min_land_vo_001", "min_land_vo_002", "min_land_vo_003", "min_land_vo_004", "min_land_vo_005", "min_land_vo_006", "min_land_vo_007", "min_land_vo_008"};
constexpr std::string_view c3_water_land_vo[]{"min_water_land_vo_001", "min_water_land_vo_002", "min_water_land_vo_003", "min_water_land_vo_004", "min_water_land_vo_005", "min_water_land_vo_006", "min_water_land_vo_007", "min_water_land_vo_008"};
constexpr std::string_view c3_fall_hurt_vo[]{"min_water_land_vo_001", "min_water_land_vo_002", "min_water_land_vo_003", "min_water_land_vo_004", "min_water_land_vo_005", "min_water_land_vo_006", "min_water_land_vo_007", "min_water_land_vo_008"};
constexpr std::string_view c4_death_sound[]{"vo_zombiedeath_001", "vo_zombiedeath_002", "vo_zombiedeath_003", "vo_zombiedeath_004", "vo_zombiedeath_005", "vo_zombiedeath_006", "vo_zombiedeath_007", "vo_zombiedeath_008", "vo_zombiedeath_009", "vo_zombiedeath_010"};
constexpr std::string_view c4_periodic_sound[]{"vo_zombiegroan_001", "vo_zombiegroan_002", "vo_zombiegroan_003", "vo_zombiegroan_004", "vo_zombiegroan_005", "vo_zombiegroan_006", "vo_zombiegroan_007", "vo_zombiegroan_008", "vo_zombiegroan_009", "vo_zombiegroan_010", "vo_zombiegroan_011", "vo_zombiegroan_012", "vo_zombiegroan_013", "vo_zombiegroan_014", "vo_zombiegroan_015", "vo_zombiegroan_016"};
constexpr std::string_view c5_death_sound[]{"classic_death_vo"};
constexpr std::string_view c5_fall_hurt_vo[]{"classic_fallhurt_vo"};
constexpr std::string_view c6_death_sound[]{"gang_death_vo_001", "gang_death_vo_002", "gang_death_vo_003", "gang_death_vo_004", "gang_death_vo_005", "gang_death_vo_006", "gang_death_vo_007", "gang_death_vo_008"};
constexpr std::string_view c6_spawn_vo[]{"gang_spawn_vo_001", "gang_spawn_vo_002", "gang_spawn_vo_003", "gang_spawn_vo_004", "gang_spawn_vo_005", "gang_spawn_vo_006"};
constexpr std::string_view c6_jump_vo[]{"gang_jump_vo_001", "gang_jump_vo_002", "gang_jump_vo_003", "gang_jump_vo_004", "gang_jump_vo_005", "gang_jump_vo_006", "gang_jump_vo_007", "gang_jump_vo_008"};
constexpr std::string_view c6_water_jump_vo[]{"gang_water_jump_vo_001", "gang_water_jump_vo_002", "gang_water_jump_vo_003", "gang_water_jump_vo_004", "gang_water_jump_vo_005", "gang_water_jump_vo_006", "gang_water_jump_vo_007", "gang_water_jump_vo_008"};
constexpr std::string_view c6_land_vo[]{"gang_land_vo_001", "gang_land_vo_002", "gang_land_vo_003", "gang_land_vo_004", "gang_land_vo_005", "gang_land_vo_006", "gang_land_vo_007", "gang_land_vo_008"};
constexpr std::string_view c6_water_land_vo[]{"gang_water_land_vo_001", "gang_water_land_vo_002", "gang_water_land_vo_003", "gang_water_land_vo_004", "gang_water_land_vo_005", "gang_water_land_vo_006", "gang_water_land_vo_007", "gang_water_land_vo_008"};
constexpr std::string_view c6_fall_hurt_vo[]{"gang_water_land_vo_001", "gang_water_land_vo_002", "gang_water_land_vo_003", "gang_water_land_vo_004", "gang_water_land_vo_005", "gang_water_land_vo_006", "gang_water_land_vo_007", "gang_water_land_vo_008"};
constexpr std::string_view c7_death_sound[]{"gang_death_vo_001", "gang_death_vo_002", "gang_death_vo_003", "gang_death_vo_004", "gang_death_vo_005", "gang_death_vo_006", "gang_death_vo_007", "gang_death_vo_008"};
constexpr std::string_view c7_spawn_vo[]{"gang_spawn_vo_001", "gang_spawn_vo_002", "gang_spawn_vo_003", "gang_spawn_vo_004", "gang_spawn_vo_005", "gang_spawn_vo_006"};
constexpr std::string_view c7_jump_vo[]{"gang_jump_vo_001", "gang_jump_vo_002", "gang_jump_vo_003", "gang_jump_vo_004", "gang_jump_vo_005", "gang_jump_vo_006", "gang_jump_vo_007", "gang_jump_vo_008"};
constexpr std::string_view c7_water_jump_vo[]{"gang_water_jump_vo_001", "gang_water_jump_vo_002", "gang_water_jump_vo_003", "gang_water_jump_vo_004", "gang_water_jump_vo_005", "gang_water_jump_vo_006", "gang_water_jump_vo_007", "gang_water_jump_vo_008"};
constexpr std::string_view c7_land_vo[]{"gang_land_vo_001", "gang_land_vo_002", "gang_land_vo_003", "gang_land_vo_004", "gang_land_vo_005", "gang_land_vo_006", "gang_land_vo_007", "gang_land_vo_008"};
constexpr std::string_view c7_water_land_vo[]{"gang_water_land_vo_001", "gang_water_land_vo_002", "gang_water_land_vo_003", "gang_water_land_vo_004", "gang_water_land_vo_005", "gang_water_land_vo_006", "gang_water_land_vo_007", "gang_water_land_vo_008"};
constexpr std::string_view c7_fall_hurt_vo[]{"gang_water_land_vo_001", "gang_water_land_vo_002", "gang_water_land_vo_003", "gang_water_land_vo_004", "gang_water_land_vo_005", "gang_water_land_vo_006", "gang_water_land_vo_007", "gang_water_land_vo_008"};
constexpr std::string_view c8_death_sound[]{"gang_death_vo_001", "gang_death_vo_002", "gang_death_vo_003", "gang_death_vo_004", "gang_death_vo_005", "gang_death_vo_006", "gang_death_vo_007", "gang_death_vo_008"};
constexpr std::string_view c8_spawn_vo[]{"gang_spawn_vo_001", "gang_spawn_vo_002", "gang_spawn_vo_003", "gang_spawn_vo_004", "gang_spawn_vo_005", "gang_spawn_vo_006"};
constexpr std::string_view c8_jump_vo[]{"gang_jump_vo_001", "gang_jump_vo_002", "gang_jump_vo_003", "gang_jump_vo_004", "gang_jump_vo_005", "gang_jump_vo_006", "gang_jump_vo_007", "gang_jump_vo_008"};
constexpr std::string_view c8_water_jump_vo[]{"gang_water_jump_vo_001", "gang_water_jump_vo_002", "gang_water_jump_vo_003", "gang_water_jump_vo_004", "gang_water_jump_vo_005", "gang_water_jump_vo_006", "gang_water_jump_vo_007", "gang_water_jump_vo_008"};
constexpr std::string_view c8_land_vo[]{"gang_land_vo_001", "gang_land_vo_002", "gang_land_vo_003", "gang_land_vo_004", "gang_land_vo_005", "gang_land_vo_006", "gang_land_vo_007", "gang_land_vo_008"};
constexpr std::string_view c8_water_land_vo[]{"gang_water_land_vo_001", "gang_water_land_vo_002", "gang_water_land_vo_003", "gang_water_land_vo_004", "gang_water_land_vo_005", "gang_water_land_vo_006", "gang_water_land_vo_007", "gang_water_land_vo_008"};
constexpr std::string_view c8_fall_hurt_vo[]{"gang_water_land_vo_001", "gang_water_land_vo_002", "gang_water_land_vo_003", "gang_water_land_vo_004", "gang_water_land_vo_005", "gang_water_land_vo_006", "gang_water_land_vo_007", "gang_water_land_vo_008"};
constexpr std::string_view c9_death_sound[]{"gang_death_vo_001", "gang_death_vo_002", "gang_death_vo_003", "gang_death_vo_004", "gang_death_vo_005", "gang_death_vo_006", "gang_death_vo_007", "gang_death_vo_008"};
constexpr std::string_view c9_spawn_vo[]{"gang_spawn_vo_001", "gang_spawn_vo_002", "gang_spawn_vo_003", "gang_spawn_vo_004", "gang_spawn_vo_005", "gang_spawn_vo_006"};
constexpr std::string_view c9_jump_vo[]{"gang_jump_vo_001", "gang_jump_vo_002", "gang_jump_vo_003", "gang_jump_vo_004", "gang_jump_vo_005", "gang_jump_vo_006", "gang_jump_vo_007", "gang_jump_vo_008"};
constexpr std::string_view c9_water_jump_vo[]{"gang_water_jump_vo_001", "gang_water_jump_vo_002", "gang_water_jump_vo_003", "gang_water_jump_vo_004", "gang_water_jump_vo_005", "gang_water_jump_vo_006", "gang_water_jump_vo_007", "gang_water_jump_vo_008"};
constexpr std::string_view c9_land_vo[]{"gang_land_vo_001", "gang_land_vo_002", "gang_land_vo_003", "gang_land_vo_004", "gang_land_vo_005", "gang_land_vo_006", "gang_land_vo_007", "gang_land_vo_008"};
constexpr std::string_view c9_water_land_vo[]{"gang_water_land_vo_001", "gang_water_land_vo_002", "gang_water_land_vo_003", "gang_water_land_vo_004", "gang_water_land_vo_005", "gang_water_land_vo_006", "gang_water_land_vo_007", "gang_water_land_vo_008"};
constexpr std::string_view c9_fall_hurt_vo[]{"gang_water_land_vo_001", "gang_water_land_vo_002", "gang_water_land_vo_003", "gang_water_land_vo_004", "gang_water_land_vo_005", "gang_water_land_vo_006", "gang_water_land_vo_007", "gang_water_land_vo_008"};
constexpr std::string_view c10_death_sound[]{"gang_death_vo_001", "gang_death_vo_002", "gang_death_vo_003", "gang_death_vo_004", "gang_death_vo_005", "gang_death_vo_006", "gang_death_vo_007", "gang_death_vo_008"};
constexpr std::string_view c10_spawn_vo[]{"gang_spawn_vo_001", "gang_spawn_vo_002", "gang_spawn_vo_003", "gang_spawn_vo_004", "gang_spawn_vo_005", "gang_spawn_vo_006"};
constexpr std::string_view c10_jump_vo[]{"gang_jump_vo_001", "gang_jump_vo_002", "gang_jump_vo_003", "gang_jump_vo_004", "gang_jump_vo_005", "gang_jump_vo_006", "gang_jump_vo_007", "gang_jump_vo_008"};
constexpr std::string_view c10_water_jump_vo[]{"gang_water_jump_vo_001", "gang_water_jump_vo_002", "gang_water_jump_vo_003", "gang_water_jump_vo_004", "gang_water_jump_vo_005", "gang_water_jump_vo_006", "gang_water_jump_vo_007", "gang_water_jump_vo_008"};
constexpr std::string_view c10_land_vo[]{"gang_land_vo_001", "gang_land_vo_002", "gang_land_vo_003", "gang_land_vo_004", "gang_land_vo_005", "gang_land_vo_006", "gang_land_vo_007", "gang_land_vo_008"};
constexpr std::string_view c10_water_land_vo[]{"gang_water_land_vo_001", "gang_water_land_vo_002", "gang_water_land_vo_003", "gang_water_land_vo_004", "gang_water_land_vo_005", "gang_water_land_vo_006", "gang_water_land_vo_007", "gang_water_land_vo_008"};
constexpr std::string_view c10_fall_hurt_vo[]{"gang_water_land_vo_001", "gang_water_land_vo_002", "gang_water_land_vo_003", "gang_water_land_vo_004", "gang_water_land_vo_005", "gang_water_land_vo_006", "gang_water_land_vo_007", "gang_water_land_vo_008"};
constexpr std::string_view c11_death_sound[]{"gang_death_vo_001", "gang_death_vo_002", "gang_death_vo_003", "gang_death_vo_004", "gang_death_vo_005", "gang_death_vo_006", "gang_death_vo_007", "gang_death_vo_008"};
constexpr std::string_view c11_spawn_vo[]{"gang_spawn_vo_001", "gang_spawn_vo_002", "gang_spawn_vo_003", "gang_spawn_vo_004", "gang_spawn_vo_005", "gang_spawn_vo_006"};
constexpr std::string_view c11_jump_vo[]{"gang_jump_vo_001", "gang_jump_vo_002", "gang_jump_vo_003", "gang_jump_vo_004", "gang_jump_vo_005", "gang_jump_vo_006", "gang_jump_vo_007", "gang_jump_vo_008"};
constexpr std::string_view c11_water_jump_vo[]{"gang_water_jump_vo_001", "gang_water_jump_vo_002", "gang_water_jump_vo_003", "gang_water_jump_vo_004", "gang_water_jump_vo_005", "gang_water_jump_vo_006", "gang_water_jump_vo_007", "gang_water_jump_vo_008"};
constexpr std::string_view c11_land_vo[]{"gang_land_vo_001", "gang_land_vo_002", "gang_land_vo_003", "gang_land_vo_004", "gang_land_vo_005", "gang_land_vo_006", "gang_land_vo_007", "gang_land_vo_008"};
constexpr std::string_view c11_water_land_vo[]{"gang_water_land_vo_001", "gang_water_land_vo_002", "gang_water_land_vo_003", "gang_water_land_vo_004", "gang_water_land_vo_005", "gang_water_land_vo_006", "gang_water_land_vo_007", "gang_water_land_vo_008"};
constexpr std::string_view c11_fall_hurt_vo[]{"gang_water_land_vo_001", "gang_water_land_vo_002", "gang_water_land_vo_003", "gang_water_land_vo_004", "gang_water_land_vo_005", "gang_water_land_vo_006", "gang_water_land_vo_007", "gang_water_land_vo_008"};
constexpr std::string_view c12_death_sound[]{"eng_death_vo_001", "eng_death_vo_002", "eng_death_vo_003", "eng_death_vo_004", "eng_death_vo_005", "eng_death_vo_006", "eng_death_vo_007", "eng_death_vo_008"};
constexpr std::string_view c12_spawn_vo[]{"eng_spawn_vo_001", "eng_spawn_vo_002", "eng_spawn_vo_003", "eng_spawn_vo_004", "eng_spawn_vo_005"};
constexpr std::string_view c12_jump_vo[]{"eng_jump_vo_001", "eng_jump_vo_002", "eng_jump_vo_003", "eng_jump_vo_004", "eng_jump_vo_005", "eng_jump_vo_006", "eng_jump_vo_007", "eng_jump_vo_008"};
constexpr std::string_view c12_water_jump_vo[]{"eng_water_jump_vo_001", "eng_water_jump_vo_002", "eng_water_jump_vo_003", "eng_water_jump_vo_004", "eng_water_jump_vo_005", "eng_water_jump_vo_006", "eng_water_jump_vo_007", "eng_water_jump_vo_008"};
constexpr std::string_view c12_land_vo[]{"eng_land_vo_001", "eng_land_vo_002", "eng_land_vo_003", "eng_land_vo_004", "eng_land_vo_005", "eng_land_vo_006", "eng_land_vo_007", "eng_land_vo_008"};
constexpr std::string_view c12_water_land_vo[]{"eng_water_land_vo_001", "eng_water_land_vo_002", "eng_water_land_vo_003", "eng_water_land_vo_004", "eng_water_land_vo_005", "eng_water_land_vo_006", "eng_water_land_vo_007", "eng_water_land_vo_008"};
constexpr std::string_view c12_fall_hurt_vo[]{"eng_water_land_vo_001", "eng_water_land_vo_002", "eng_water_land_vo_003", "eng_water_land_vo_004", "eng_water_land_vo_005", "eng_water_land_vo_006", "eng_water_land_vo_007", "eng_water_land_vo_008"};
constexpr std::string_view c14_death_sound[]{"vo_zombiedeath_001", "vo_zombiedeath_002", "vo_zombiedeath_003", "vo_zombiedeath_004", "vo_zombiedeath_005", "vo_zombiedeath_006", "vo_zombiedeath_007", "vo_zombiedeath_008", "vo_zombiedeath_009", "vo_zombiedeath_010"};
constexpr std::string_view c14_periodic_sound[]{"vo_zombiegroan_001", "vo_zombiegroan_002", "vo_zombiegroan_003", "vo_zombiegroan_004", "vo_zombiegroan_005", "vo_zombiegroan_006", "vo_zombiegroan_007", "vo_zombiegroan_008", "vo_zombiegroan_009", "vo_zombiegroan_010", "vo_zombiegroan_011", "vo_zombiegroan_012", "vo_zombiegroan_013", "vo_zombiegroan_014", "vo_zombiegroan_015", "vo_zombiegroan_016"};
constexpr std::string_view c15_death_sound[]{"vo_zombiedeath_001", "vo_zombiedeath_002", "vo_zombiedeath_003", "vo_zombiedeath_004", "vo_zombiedeath_005", "vo_zombiedeath_006", "vo_zombiedeath_007", "vo_zombiedeath_008", "vo_zombiedeath_009", "vo_zombiedeath_010"};
constexpr std::string_view c15_periodic_sound[]{"vo_zombiegroan_001", "vo_zombiegroan_002", "vo_zombiegroan_003", "vo_zombiegroan_004", "vo_zombiegroan_005", "vo_zombiegroan_006", "vo_zombiegroan_007", "vo_zombiegroan_008", "vo_zombiegroan_009", "vo_zombiegroan_010", "vo_zombiegroan_011", "vo_zombiegroan_012", "vo_zombiegroan_013", "vo_zombiegroan_014", "vo_zombiegroan_015", "vo_zombiegroan_016"};
constexpr std::string_view c16_death_sound[]{"AoS_vox_SPECIALIST_emote_death_001", "AoS_vox_SPECIALIST_emote_death_002", "AoS_vox_SPECIALIST_emote_death_003", "AoS_vox_SPECIALIST_emote_death_004", "AoS_vox_SPECIALIST_emote_death_005", "AoS_vox_SPECIALIST_emote_death_006", "AoS_vox_SPECIALIST_emote_death_007", "AoS_vox_SPECIALIST_emote_death_008"};
constexpr std::string_view c16_spawn_vo[]{"AoS_vox_SPECIALIST_spawn_001", "AoS_vox_SPECIALIST_spawn_002", "AoS_vox_SPECIALIST_spawn_003", "AoS_vox_SPECIALIST_spawn_004", "AoS_vox_SPECIALIST_spawn_005"};
constexpr std::string_view c16_jump_vo[]{"AoS_vox_SPECIALIST_emote_jump_001", "AoS_vox_SPECIALIST_emote_jump_002", "AoS_vox_SPECIALIST_emote_jump_003", "AoS_vox_SPECIALIST_emote_jump_004", "AoS_vox_SPECIALIST_emote_jump_005", "AoS_vox_SPECIALIST_emote_jump_006", "AoS_vox_SPECIALIST_emote_jump_007", "AoS_vox_SPECIALIST_emote_jump_008"};
constexpr std::string_view c16_water_jump_vo[]{"AoS_vox_SPECIALIST_emote_jump_001", "AoS_vox_SPECIALIST_emote_jump_002", "AoS_vox_SPECIALIST_emote_jump_003", "AoS_vox_SPECIALIST_emote_jump_004", "AoS_vox_SPECIALIST_emote_jump_005", "AoS_vox_SPECIALIST_emote_jump_006", "AoS_vox_SPECIALIST_emote_jump_007", "AoS_vox_SPECIALIST_emote_jump_008"};
constexpr std::string_view c16_land_vo[]{"AoS_vox_SPECIALIST_emote_land_001", "AoS_vox_SPECIALIST_emote_land_002", "AoS_vox_SPECIALIST_emote_land_003", "AoS_vox_SPECIALIST_emote_land_004", "AoS_vox_SPECIALIST_emote_land_005", "AoS_vox_SPECIALIST_emote_land_006", "AoS_vox_SPECIALIST_emote_land_007", "AoS_vox_SPECIALIST_emote_land_008"};
constexpr std::string_view c16_water_land_vo[]{"AoS_vox_SPECIALIST_emote_land_001", "AoS_vox_SPECIALIST_emote_land_002", "AoS_vox_SPECIALIST_emote_land_003", "AoS_vox_SPECIALIST_emote_land_004", "AoS_vox_SPECIALIST_emote_land_005", "AoS_vox_SPECIALIST_emote_land_006", "AoS_vox_SPECIALIST_emote_land_007", "AoS_vox_SPECIALIST_emote_land_008"};
constexpr std::string_view c16_fall_hurt_vo[]{"AoS_vox_SPECIALIST_emote_impact_fallen_001", "AoS_vox_SPECIALIST_emote_impact_fallen_002", "AoS_vox_SPECIALIST_emote_impact_fallen_003", "AoS_vox_SPECIALIST_emote_impact_fallen_004", "AoS_vox_SPECIALIST_emote_impact_fallen_005", "AoS_vox_SPECIALIST_emote_impact_fallen_006", "AoS_vox_SPECIALIST_emote_impact_fallen_007", "AoS_vox_SPECIALIST_emote_impact_fallen_008"};
constexpr std::string_view c17_death_sound[]{"AoS_vox_MEDIC_emote_death_001", "AoS_vox_MEDIC_emote_death_002", "AoS_vox_MEDIC_emote_death_003", "AoS_vox_MEDIC_emote_death_004", "AoS_vox_MEDIC_emote_death_005", "AoS_vox_MEDIC_emote_death_006", "AoS_vox_MEDIC_emote_death_007", "AoS_vox_MEDIC_emote_death_008"};
constexpr std::string_view c17_spawn_vo[]{"AoS_vox_MEDIC_spawn_001", "AoS_vox_MEDIC_spawn_002", "AoS_vox_MEDIC_spawn_003", "AoS_vox_MEDIC_spawn_004", "AoS_vox_MEDIC_spawn_005"};
constexpr std::string_view c17_jump_vo[]{"AoS_vox_MEDIC_emote_jump_001", "AoS_vox_MEDIC_emote_jump_002", "AoS_vox_MEDIC_emote_jump_003", "AoS_vox_MEDIC_emote_jump_004", "AoS_vox_MEDIC_emote_jump_005", "AoS_vox_MEDIC_emote_jump_006", "AoS_vox_MEDIC_emote_jump_007", "AoS_vox_MEDIC_emote_jump_008"};
constexpr std::string_view c17_water_jump_vo[]{"AoS_vox_MEDIC_emote_jump_001", "AoS_vox_MEDIC_emote_jump_002", "AoS_vox_MEDIC_emote_jump_003", "AoS_vox_MEDIC_emote_jump_004", "AoS_vox_MEDIC_emote_jump_005", "AoS_vox_MEDIC_emote_jump_006", "AoS_vox_MEDIC_emote_jump_007", "AoS_vox_MEDIC_emote_jump_008"};
constexpr std::string_view c17_land_vo[]{"AoS_vox_MEDIC_emote_land_001", "AoS_vox_MEDIC_emote_land_002", "AoS_vox_MEDIC_emote_land_003", "AoS_vox_MEDIC_emote_land_004", "AoS_vox_MEDIC_emote_land_005", "AoS_vox_MEDIC_emote_land_006", "AoS_vox_MEDIC_emote_land_007", "AoS_vox_MEDIC_emote_land_008"};
constexpr std::string_view c17_water_land_vo[]{"AoS_vox_MEDIC_emote_land_001", "AoS_vox_MEDIC_emote_land_002", "AoS_vox_MEDIC_emote_land_003", "AoS_vox_MEDIC_emote_land_004", "AoS_vox_MEDIC_emote_land_005", "AoS_vox_MEDIC_emote_land_006", "AoS_vox_MEDIC_emote_land_007", "AoS_vox_MEDIC_emote_land_008"};
constexpr std::string_view c17_fall_hurt_vo[]{"AoS_vox_MEDIC_emote_impact_fallen_001", "AoS_vox_MEDIC_emote_impact_fallen_002", "AoS_vox_MEDIC_emote_impact_fallen_003", "AoS_vox_MEDIC_emote_impact_fallen_004", "AoS_vox_MEDIC_emote_impact_fallen_005", "AoS_vox_MEDIC_emote_impact_fallen_006", "AoS_vox_MEDIC_emote_impact_fallen_007", "AoS_vox_MEDIC_emote_impact_fallen_008"};

constexpr ClassVoiceSet voices[]{
    ClassVoiceSet{0U, {c0_death_sound, 100U, false}, {{}, 0U, false}, {c0_spawn_vo, 25U, false}, {c0_jump_vo, 33U, true}, {c0_water_jump_vo, 66U, true}, {c0_land_vo, 33U, true}, {c0_water_land_vo, 66U, true}, {c0_fall_hurt_vo, 100U, false}},
    ClassVoiceSet{1U, {c1_death_sound, 100U, false}, {{}, 0U, false}, {c1_spawn_vo, 25U, false}, {c1_jump_vo, 33U, true}, {c1_water_jump_vo, 66U, true}, {c1_land_vo, 33U, true}, {c1_water_land_vo, 66U, true}, {c1_fall_hurt_vo, 100U, false}},
    ClassVoiceSet{2U, {c2_death_sound, 100U, false}, {{}, 0U, false}, {c2_spawn_vo, 25U, false}, {c2_jump_vo, 33U, true}, {c2_water_jump_vo, 66U, true}, {c2_land_vo, 33U, true}, {c2_water_land_vo, 66U, true}, {c2_fall_hurt_vo, 100U, false}},
    ClassVoiceSet{3U, {c3_death_sound, 100U, false}, {{}, 0U, false}, {c3_spawn_vo, 25U, false}, {c3_jump_vo, 33U, true}, {c3_water_jump_vo, 66U, true}, {c3_land_vo, 33U, true}, {c3_water_land_vo, 66U, true}, {c3_fall_hurt_vo, 100U, false}},
    ClassVoiceSet{4U, {c4_death_sound, 100U, false}, {c4_periodic_sound, 100U, false}, {{}, 0U, false}, {{}, 0U, false}, {{}, 0U, false}, {{}, 0U, false}, {{}, 0U, false}, {{}, 0U, false}},
    ClassVoiceSet{5U, {c5_death_sound, 100U, false}, {{}, 0U, false}, {{}, 0U, false}, {{}, 0U, false}, {{}, 0U, false}, {{}, 0U, false}, {{}, 0U, false}, {c5_fall_hurt_vo, 100U, false}},
    ClassVoiceSet{6U, {c6_death_sound, 100U, false}, {{}, 0U, false}, {c6_spawn_vo, 25U, false}, {c6_jump_vo, 33U, true}, {c6_water_jump_vo, 66U, true}, {c6_land_vo, 33U, true}, {c6_water_land_vo, 66U, true}, {c6_fall_hurt_vo, 100U, false}},
    ClassVoiceSet{7U, {c7_death_sound, 100U, false}, {{}, 0U, false}, {c7_spawn_vo, 25U, false}, {c7_jump_vo, 33U, true}, {c7_water_jump_vo, 66U, true}, {c7_land_vo, 33U, true}, {c7_water_land_vo, 66U, true}, {c7_fall_hurt_vo, 100U, false}},
    ClassVoiceSet{8U, {c8_death_sound, 100U, false}, {{}, 0U, false}, {c8_spawn_vo, 25U, false}, {c8_jump_vo, 33U, true}, {c8_water_jump_vo, 66U, true}, {c8_land_vo, 33U, true}, {c8_water_land_vo, 66U, true}, {c8_fall_hurt_vo, 100U, false}},
    ClassVoiceSet{9U, {c9_death_sound, 100U, false}, {{}, 0U, false}, {c9_spawn_vo, 25U, false}, {c9_jump_vo, 33U, true}, {c9_water_jump_vo, 66U, true}, {c9_land_vo, 33U, true}, {c9_water_land_vo, 66U, true}, {c9_fall_hurt_vo, 100U, false}},
    ClassVoiceSet{10U, {c10_death_sound, 100U, false}, {{}, 0U, false}, {c10_spawn_vo, 25U, false}, {c10_jump_vo, 33U, true}, {c10_water_jump_vo, 66U, true}, {c10_land_vo, 33U, true}, {c10_water_land_vo, 66U, true}, {c10_fall_hurt_vo, 100U, false}},
    ClassVoiceSet{11U, {c11_death_sound, 100U, false}, {{}, 0U, false}, {c11_spawn_vo, 25U, false}, {c11_jump_vo, 33U, true}, {c11_water_jump_vo, 66U, true}, {c11_land_vo, 33U, true}, {c11_water_land_vo, 66U, true}, {c11_fall_hurt_vo, 100U, false}},
    ClassVoiceSet{12U, {c12_death_sound, 100U, false}, {{}, 0U, false}, {c12_spawn_vo, 25U, false}, {c12_jump_vo, 33U, true}, {c12_water_jump_vo, 66U, true}, {c12_land_vo, 33U, true}, {c12_water_land_vo, 66U, true}, {c12_fall_hurt_vo, 100U, false}},
    ClassVoiceSet{13U, {{}, 0U, false}, {{}, 0U, false}, {{}, 0U, false}, {{}, 0U, false}, {{}, 0U, false}, {{}, 0U, false}, {{}, 0U, false}, {{}, 0U, false}},
    ClassVoiceSet{14U, {c14_death_sound, 100U, false}, {c14_periodic_sound, 100U, false}, {{}, 0U, false}, {{}, 0U, false}, {{}, 0U, false}, {{}, 0U, false}, {{}, 0U, false}, {{}, 0U, false}},
    ClassVoiceSet{15U, {c15_death_sound, 100U, false}, {c15_periodic_sound, 100U, false}, {{}, 0U, false}, {{}, 0U, false}, {{}, 0U, false}, {{}, 0U, false}, {{}, 0U, false}, {{}, 0U, false}},
    ClassVoiceSet{16U, {c16_death_sound, 100U, false}, {{}, 0U, false}, {c16_spawn_vo, 25U, false}, {c16_jump_vo, 33U, true}, {c16_water_jump_vo, 66U, true}, {c16_land_vo, 33U, true}, {c16_water_land_vo, 66U, true}, {c16_fall_hurt_vo, 100U, false}},
    ClassVoiceSet{17U, {c17_death_sound, 100U, false}, {{}, 0U, false}, {c17_spawn_vo, 25U, false}, {c17_jump_vo, 33U, true}, {c17_water_jump_vo, 66U, true}, {c17_land_vo, 33U, true}, {c17_water_land_vo, 66U, true}, {c17_fall_hurt_vo, 100U, false}},
};

} // namespace

const ClassVoiceSet* find_class_voice(std::uint8_t class_id) noexcept {
    for (const auto& entry : voices) {
        if (entry.class_id == class_id) {
            return &entry;
        }
    }
    return nullptr;
}

std::span<const ClassVoiceSet> class_voice_table() noexcept {
    return voices;
}

} // namespace battlespades::world
