// Generated by tools/generate_class_catalog.py; do not edit.
#include "battlespades/world/class_catalog.hpp"

#include "battlespades/world/weapon_catalog.hpp"

#include <algorithm>
#include <array>

namespace battlespades::world {
namespace {

constexpr std::array<std::uint16_t, 2U> class_0_group_0{{2U, 1U}};
constexpr std::array<std::uint16_t, 2U> class_0_group_1{{8U, 60U}};
constexpr std::array<std::uint16_t, 2U> class_0_group_2{{12U, 13U}};
constexpr std::array<std::uint16_t, 3U> class_0_group_3{{11U, 32U, 72U}};
constexpr std::array<std::uint16_t, 3U> class_0_group_4{{0U, 8U, 7U}};
constexpr std::array<std::uint16_t, 7U> class_0_group_5{{5U, 23U, 22U, 30U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_0_group_6{{}};

constexpr std::array<std::uint16_t, 2U> class_1_group_0{{0U, 1U}};
constexpr std::array<std::uint16_t, 2U> class_1_group_1{{18U, 19U}};
constexpr std::array<std::uint16_t, 2U> class_1_group_2{{17U, 53U}};
constexpr std::array<std::uint16_t, 2U> class_1_group_3{{20U, 56U}};
constexpr std::array<std::uint16_t, 3U> class_1_group_4{{1U, 8U, 7U}};
constexpr std::array<std::uint16_t, 7U> class_1_group_5{{5U, 23U, 22U, 30U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_1_group_6{{}};

constexpr std::array<std::uint16_t, 2U> class_2_group_0{{2U, 0U}};
constexpr std::array<std::uint16_t, 1U> class_2_group_1{{7U}};
constexpr std::array<std::uint16_t, 2U> class_2_group_2{{16U, 11U}};
constexpr std::array<std::uint16_t, 2U> class_2_group_3{{67U, 66U}};
constexpr std::array<std::uint16_t, 3U> class_2_group_4{{2U, 8U, 7U}};
constexpr std::array<std::uint16_t, 7U> class_2_group_5{{5U, 23U, 22U, 30U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_2_group_6{{}};

constexpr std::array<std::uint16_t, 1U> class_3_group_0{{3U}};
constexpr std::array<std::uint16_t, 2U> class_3_group_1{{9U, 10U}};
constexpr std::array<std::uint16_t, 2U> class_3_group_2{{14U, 63U}};
constexpr std::array<std::uint16_t, 2U> class_3_group_3{{21U, 59U}};
constexpr std::array<std::uint16_t, 3U> class_3_group_4{{3U, 8U, 7U}};
constexpr std::array<std::uint16_t, 7U> class_3_group_5{{5U, 23U, 22U, 30U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_3_group_6{{}};

constexpr std::array<std::uint16_t, 0U> class_4_group_0{{}};
constexpr std::array<std::uint16_t, 1U> class_4_group_1{{24U}};
constexpr std::array<std::uint16_t, 0U> class_4_group_2{{}};
constexpr std::array<std::uint16_t, 0U> class_4_group_3{{}};
constexpr std::array<std::uint16_t, 1U> class_4_group_4{{4U}};
constexpr std::array<std::uint16_t, 1U> class_4_group_5{{28U}};
constexpr std::array<std::uint16_t, 0U> class_4_group_6{{}};

constexpr std::array<std::uint16_t, 1U> class_5_group_0{{4U}};
constexpr std::array<std::uint16_t, 3U> class_5_group_1{{6U, 38U, 37U}};
constexpr std::array<std::uint16_t, 0U> class_5_group_2{{}};
constexpr std::array<std::uint16_t, 1U> class_5_group_3{{31U}};
constexpr std::array<std::uint16_t, 0U> class_5_group_4{{}};
constexpr std::array<std::uint16_t, 4U> class_5_group_5{{5U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_5_group_6{{}};

constexpr std::array<std::uint16_t, 1U> class_6_group_0{{34U}};
constexpr std::array<std::uint16_t, 1U> class_6_group_1{{35U}};
constexpr std::array<std::uint16_t, 1U> class_6_group_2{{36U}};
constexpr std::array<std::uint16_t, 1U> class_6_group_3{{33U}};
constexpr std::array<std::uint16_t, 3U> class_6_group_4{{6U, 8U, 7U}};
constexpr std::array<std::uint16_t, 7U> class_6_group_5{{5U, 23U, 22U, 30U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_6_group_6{{}};

constexpr std::array<std::uint16_t, 1U> class_7_group_0{{34U}};
constexpr std::array<std::uint16_t, 1U> class_7_group_1{{35U}};
constexpr std::array<std::uint16_t, 1U> class_7_group_2{{36U}};
constexpr std::array<std::uint16_t, 1U> class_7_group_3{{33U}};
constexpr std::array<std::uint16_t, 3U> class_7_group_4{{6U, 8U, 7U}};
constexpr std::array<std::uint16_t, 7U> class_7_group_5{{5U, 23U, 22U, 30U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_7_group_6{{}};

constexpr std::array<std::uint16_t, 1U> class_8_group_0{{34U}};
constexpr std::array<std::uint16_t, 1U> class_8_group_1{{35U}};
constexpr std::array<std::uint16_t, 1U> class_8_group_2{{36U}};
constexpr std::array<std::uint16_t, 1U> class_8_group_3{{33U}};
constexpr std::array<std::uint16_t, 3U> class_8_group_4{{6U, 8U, 7U}};
constexpr std::array<std::uint16_t, 7U> class_8_group_5{{5U, 23U, 22U, 30U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_8_group_6{{}};

constexpr std::array<std::uint16_t, 1U> class_9_group_0{{34U}};
constexpr std::array<std::uint16_t, 1U> class_9_group_1{{35U}};
constexpr std::array<std::uint16_t, 1U> class_9_group_2{{36U}};
constexpr std::array<std::uint16_t, 1U> class_9_group_3{{33U}};
constexpr std::array<std::uint16_t, 3U> class_9_group_4{{6U, 8U, 7U}};
constexpr std::array<std::uint16_t, 7U> class_9_group_5{{5U, 23U, 22U, 30U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_9_group_6{{}};

constexpr std::array<std::uint16_t, 1U> class_10_group_0{{34U}};
constexpr std::array<std::uint16_t, 1U> class_10_group_1{{35U}};
constexpr std::array<std::uint16_t, 1U> class_10_group_2{{36U}};
constexpr std::array<std::uint16_t, 1U> class_10_group_3{{33U}};
constexpr std::array<std::uint16_t, 3U> class_10_group_4{{6U, 8U, 7U}};
constexpr std::array<std::uint16_t, 7U> class_10_group_5{{5U, 23U, 22U, 30U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_10_group_6{{}};

constexpr std::array<std::uint16_t, 1U> class_11_group_0{{34U}};
constexpr std::array<std::uint16_t, 1U> class_11_group_1{{35U}};
constexpr std::array<std::uint16_t, 1U> class_11_group_2{{36U}};
constexpr std::array<std::uint16_t, 1U> class_11_group_3{{33U}};
constexpr std::array<std::uint16_t, 3U> class_11_group_4{{6U, 8U, 7U}};
constexpr std::array<std::uint16_t, 7U> class_11_group_5{{5U, 23U, 22U, 30U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_11_group_6{{}};

constexpr std::array<std::uint16_t, 1U> class_12_group_0{{0U}};
constexpr std::array<std::uint16_t, 1U> class_12_group_1{{7U}};
constexpr std::array<std::uint16_t, 3U> class_12_group_2{{16U, 29U, 58U}};
constexpr std::array<std::uint16_t, 2U> class_12_group_3{{68U, 64U}};
constexpr std::array<std::uint16_t, 3U> class_12_group_4{{9U, 8U, 7U}};
constexpr std::array<std::uint16_t, 7U> class_12_group_5{{5U, 23U, 22U, 30U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_12_group_6{{}};

constexpr std::array<std::uint16_t, 1U> class_13_group_0{{45U}};
constexpr std::array<std::uint16_t, 1U> class_13_group_1{{47U}};
constexpr std::array<std::uint16_t, 1U> class_13_group_2{{48U}};
constexpr std::array<std::uint16_t, 1U> class_13_group_3{{69U}};
constexpr std::array<std::uint16_t, 3U> class_13_group_4{{10U, 8U, 7U}};
constexpr std::array<std::uint16_t, 9U> class_13_group_5{{5U, 43U, 22U, 30U, 42U, 41U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 1U> class_13_group_6{{0U}};

constexpr std::array<std::uint16_t, 0U> class_14_group_0{{}};
constexpr std::array<std::uint16_t, 1U> class_14_group_1{{24U}};
constexpr std::array<std::uint16_t, 0U> class_14_group_2{{}};
constexpr std::array<std::uint16_t, 0U> class_14_group_3{{}};
constexpr std::array<std::uint16_t, 1U> class_14_group_4{{4U}};
constexpr std::array<std::uint16_t, 1U> class_14_group_5{{28U}};
constexpr std::array<std::uint16_t, 0U> class_14_group_6{{}};

constexpr std::array<std::uint16_t, 0U> class_15_group_0{{}};
constexpr std::array<std::uint16_t, 1U> class_15_group_1{{24U}};
constexpr std::array<std::uint16_t, 0U> class_15_group_2{{}};
constexpr std::array<std::uint16_t, 0U> class_15_group_3{{}};
constexpr std::array<std::uint16_t, 1U> class_15_group_4{{4U}};
constexpr std::array<std::uint16_t, 1U> class_15_group_5{{28U}};
constexpr std::array<std::uint16_t, 0U> class_15_group_6{{}};

constexpr std::array<std::uint16_t, 2U> class_16_group_0{{2U, 50U}};
constexpr std::array<std::uint16_t, 2U> class_16_group_1{{62U, 7U}};
constexpr std::array<std::uint16_t, 2U> class_16_group_2{{53U, 55U}};
constexpr std::array<std::uint16_t, 2U> class_16_group_3{{54U, 57U}};
constexpr std::array<std::uint16_t, 3U> class_16_group_4{{13U, 8U, 7U}};
constexpr std::array<std::uint16_t, 7U> class_16_group_5{{5U, 23U, 22U, 30U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_16_group_6{{}};

constexpr std::array<std::uint16_t, 2U> class_17_group_0{{0U, 49U}};
constexpr std::array<std::uint16_t, 2U> class_17_group_1{{61U, 10U}};
constexpr std::array<std::uint16_t, 1U> class_17_group_2{{52U}};
constexpr std::array<std::uint16_t, 1U> class_17_group_3{{51U}};
constexpr std::array<std::uint16_t, 3U> class_17_group_4{{14U, 8U, 7U}};
constexpr std::array<std::uint16_t, 7U> class_17_group_5{{5U, 23U, 22U, 30U, 25U, 26U, 30U}};
constexpr std::array<std::uint16_t, 0U> class_17_group_6{{}};

constexpr std::array<ClassDefinition, retail_class_count> classes{{
    ClassDefinition{
        0U, "SOLDIER", "Soldier",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Soldier_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Soldier_Body.kv6", {-1.0F, 1.5F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Soldier_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Soldier_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_Soldier_Arms_Upper.kv6", "kv6/Character_Soldier_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_0_group_0}, std::span<const std::uint16_t>{class_0_group_1}, std::span<const std::uint16_t>{class_0_group_2}, std::span<const std::uint16_t>{class_0_group_3}, std::span<const std::uint16_t>{class_0_group_4}, std::span<const std::uint16_t>{class_0_group_5}, std::span<const std::uint16_t>{class_0_group_6}},
        200U, 1000U,
        {"png/ui/in_game_menus/select_class/soldier_character_team1.png", "png/ui/in_game_menus/select_class/soldier_character_team2.png"},
        {"png/ui/in_game_menus/select_class/soldier_icon_team1.png", "png/ui/in_game_menus/select_class/soldier_icon_team2.png"}, "", 1.0},
    ClassDefinition{
        1U, "SCOUT", "Scout",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Scout_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Scout_Body.kv6", {0.0F, 1.5F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Scout_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Scout_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_Scout_Arms_Upper.kv6", "kv6/Character_Scout_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_1_group_0}, std::span<const std::uint16_t>{class_1_group_1}, std::span<const std::uint16_t>{class_1_group_2}, std::span<const std::uint16_t>{class_1_group_3}, std::span<const std::uint16_t>{class_1_group_4}, std::span<const std::uint16_t>{class_1_group_5}, std::span<const std::uint16_t>{class_1_group_6}},
        400U, 1000U,
        {"png/ui/in_game_menus/select_class/scout_character_team1.png", "png/ui/in_game_menus/select_class/scout_character_team2.png"},
        {"png/ui/in_game_menus/select_class/scout_icon_team1.png", "png/ui/in_game_menus/select_class/scout_icon_team2.png"}, "", 1.43},
    ClassDefinition{
        2U, "ROCKETEER", "Rocketeer",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Rocketeer_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Rocketeer_Body.kv6", {0.0F, 0.0F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Rocketeer_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Rocketeer_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_Rocketeer_Arms_Upper.kv6", "kv6/Character_Rocketeer_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_2_group_0}, std::span<const std::uint16_t>{class_2_group_1}, std::span<const std::uint16_t>{class_2_group_2}, std::span<const std::uint16_t>{class_2_group_3}, std::span<const std::uint16_t>{class_2_group_4}, std::span<const std::uint16_t>{class_2_group_5}, std::span<const std::uint16_t>{class_2_group_6}},
        500U, 1500U,
        {"png/ui/in_game_menus/select_class/pilot_character_team1.png", "png/ui/in_game_menus/select_class/pilot_character_team2.png"},
        {"png/ui/in_game_menus/select_class/pilot_icon_team1.png", "png/ui/in_game_menus/select_class/pilot_icon_team2.png"}, "", 1.43},
    ClassDefinition{
        3U, "MINER", "Miner",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Miner_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Miner_Body.kv6", {0.0F, 0.0F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Miner_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Miner_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_Miner_Arms_Upper.kv6", "kv6/Character_Miner_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_3_group_0}, std::span<const std::uint16_t>{class_3_group_1}, std::span<const std::uint16_t>{class_3_group_2}, std::span<const std::uint16_t>{class_3_group_3}, std::span<const std::uint16_t>{class_3_group_4}, std::span<const std::uint16_t>{class_3_group_5}, std::span<const std::uint16_t>{class_3_group_6}},
        0U, 1000U,
        {"png/ui/in_game_menus/select_class/miner_character_team1.png", "png/ui/in_game_menus/select_class/miner_character_team2.png"},
        {"png/ui/in_game_menus/select_class/miner_icon_team1.png", "png/ui/in_game_menus/select_class/miner_icon_team2.png"}, "", 1.1765},
    ClassDefinition{
        4U, "ZOMBIE", "Zombie",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Zombie_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Zombie_Body.kv6", {0.0F, 0.0F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, 0.0F, 0.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Zombie_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Zombie_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"", ""},
        {std::span<const std::uint16_t>{class_4_group_0}, std::span<const std::uint16_t>{class_4_group_1}, std::span<const std::uint16_t>{class_4_group_2}, std::span<const std::uint16_t>{class_4_group_3}, std::span<const std::uint16_t>{class_4_group_4}, std::span<const std::uint16_t>{class_4_group_5}, std::span<const std::uint16_t>{class_4_group_6}},
        1000U, 2000U,
        {"png/ui/in_game_menus/select_class/zombie_character_team1.png", "png/ui/in_game_menus/select_class/zombie_character_team2.png"},
        {"png/ui/in_game_menus/select_class/zombie_icon.png", "png/ui/in_game_menus/select_class/zombie_icon.png"}, "", 0.6},
    ClassDefinition{
        5U, "CLASSIC_SOLDIER", "Classic Soldier",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Deuce_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Deuce_Body.kv6", {-1.0F, 1.5F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Deuce_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Deuce_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_Deuce_Arms_Upper.kv6", "kv6/Character_Deuce_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_5_group_0}, std::span<const std::uint16_t>{class_5_group_1}, std::span<const std::uint16_t>{class_5_group_2}, std::span<const std::uint16_t>{class_5_group_3}, std::span<const std::uint16_t>{class_5_group_4}, std::span<const std::uint16_t>{class_5_group_5}, std::span<const std::uint16_t>{class_5_group_6}},
        25U, 100U,
        {"png/ui/in_game_menus/select_class/classic_character_team1.png", "png/ui/in_game_menus/select_class/classic_character_team2.png"},
        {"png/ui/in_game_menus/select_class/classic_icon_team1.png", "png/ui/in_game_menus/select_class/classic_icon_team2.png"}, "", 1.0},
    ClassDefinition{
        6U, "GANGSTER_1", "Gangster 1",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Gangster1_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Gangster1_Body.kv6", {-1.0F, 1.5F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Gangster1_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Gangster1_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_Gangster1_Arms_Upper.kv6", "kv6/Character_Gangster1_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_6_group_0}, std::span<const std::uint16_t>{class_6_group_1}, std::span<const std::uint16_t>{class_6_group_2}, std::span<const std::uint16_t>{class_6_group_3}, std::span<const std::uint16_t>{class_6_group_4}, std::span<const std::uint16_t>{class_6_group_5}, std::span<const std::uint16_t>{class_6_group_6}},
        500U, 1200U,
        {"png/ui/in_game_menus/select_class/soldier_character_team1.png", "png/ui/in_game_menus/select_class/soldier_character_team2.png"},
        {"png/ui/in_game_menus/select_class/gangster1_icon_team1.png", "png/ui/in_game_menus/select_class/gangster1_icon_team2.png"}, "mafia", 1.0},
    ClassDefinition{
        7U, "GANGSTER_2", "Gangster 2",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Gangster2_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Gangster2_Body.kv6", {-1.0F, 1.5F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Gangster2_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Gangster2_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_Gangster2_Arms_Upper.kv6", "kv6/Character_Gangster2_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_7_group_0}, std::span<const std::uint16_t>{class_7_group_1}, std::span<const std::uint16_t>{class_7_group_2}, std::span<const std::uint16_t>{class_7_group_3}, std::span<const std::uint16_t>{class_7_group_4}, std::span<const std::uint16_t>{class_7_group_5}, std::span<const std::uint16_t>{class_7_group_6}},
        500U, 1200U,
        {"png/ui/in_game_menus/select_class/soldier_character_team1.png", "png/ui/in_game_menus/select_class/soldier_character_team2.png"},
        {"png/ui/in_game_menus/select_class/gangster2_icon_team1.png", "png/ui/in_game_menus/select_class/gangster2_icon_team2.png"}, "mafia", 1.0},
    ClassDefinition{
        8U, "GANGSTER_3", "Gangster 3",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Gangster3_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Gangster3_Body.kv6", {-1.0F, 1.5F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Gangster3_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Gangster3_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_Gangster3_Arms_Upper.kv6", "kv6/Character_Gangster3_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_8_group_0}, std::span<const std::uint16_t>{class_8_group_1}, std::span<const std::uint16_t>{class_8_group_2}, std::span<const std::uint16_t>{class_8_group_3}, std::span<const std::uint16_t>{class_8_group_4}, std::span<const std::uint16_t>{class_8_group_5}, std::span<const std::uint16_t>{class_8_group_6}},
        500U, 1200U,
        {"png/ui/in_game_menus/select_class/soldier_character_team1.png", "png/ui/in_game_menus/select_class/soldier_character_team2.png"},
        {"png/ui/in_game_menus/select_class/gangster3_icon_team1.png", "png/ui/in_game_menus/select_class/gangster3_icon_team2.png"}, "mafia", 1.0},
    ClassDefinition{
        9U, "GANGSTER_4", "Gangster 4",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Gangster4_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Gangster4_Body.kv6", {-1.0F, 1.5F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Gangster4_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Gangster4_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_Gangster4_Arms_Upper.kv6", "kv6/Character_Gangster4_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_9_group_0}, std::span<const std::uint16_t>{class_9_group_1}, std::span<const std::uint16_t>{class_9_group_2}, std::span<const std::uint16_t>{class_9_group_3}, std::span<const std::uint16_t>{class_9_group_4}, std::span<const std::uint16_t>{class_9_group_5}, std::span<const std::uint16_t>{class_9_group_6}},
        500U, 1200U,
        {"png/ui/in_game_menus/select_class/soldier_character_team1.png", "png/ui/in_game_menus/select_class/soldier_character_team2.png"},
        {"png/ui/in_game_menus/select_class/gangster4_icon_team1.png", "png/ui/in_game_menus/select_class/gangster4_icon_team2.png"}, "mafia", 1.0},
    ClassDefinition{
        10U, "GANGSTER_VIP_1", "Gangster VIP 1",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_GangsterVIP1_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_GangsterVIP1_Body.kv6", {-1.0F, 1.5F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_GangsterVIP1_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_GangsterVIP1_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_GangsterVIP1_Arms_Upper.kv6", "kv6/Character_GangsterVIP1_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_10_group_0}, std::span<const std::uint16_t>{class_10_group_1}, std::span<const std::uint16_t>{class_10_group_2}, std::span<const std::uint16_t>{class_10_group_3}, std::span<const std::uint16_t>{class_10_group_4}, std::span<const std::uint16_t>{class_10_group_5}, std::span<const std::uint16_t>{class_10_group_6}},
        500U, 1200U,
        {"png/ui/in_game_menus/select_class/soldier_character_team1.png", "png/ui/in_game_menus/select_class/soldier_character_team2.png"},
        {"png/ui/in_game_menus/select_class/boss_icon_team1.png", "png/ui/in_game_menus/select_class/boss_icon_team2.png"}, "mafia", 1.0},
    ClassDefinition{
        11U, "GANGSTER_VIP_2", "Gangster VIP 2",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_GangsterVIP2_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_GangsterVIP2_Body.kv6", {-1.0F, 1.5F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_GangsterVIP2_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_GangsterVIP2_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_GangsterVIP2_Arms_Upper.kv6", "kv6/Character_GangsterVIP2_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_11_group_0}, std::span<const std::uint16_t>{class_11_group_1}, std::span<const std::uint16_t>{class_11_group_2}, std::span<const std::uint16_t>{class_11_group_3}, std::span<const std::uint16_t>{class_11_group_4}, std::span<const std::uint16_t>{class_11_group_5}, std::span<const std::uint16_t>{class_11_group_6}},
        500U, 1200U,
        {"png/ui/in_game_menus/select_class/soldier_character_team1.png", "png/ui/in_game_menus/select_class/soldier_character_team2.png"},
        {"png/ui/in_game_menus/select_class/boss_icon_team1.png", "png/ui/in_game_menus/select_class/boss_icon_team2.png"}, "mafia", 1.0},
    ClassDefinition{
        12U, "ENGINEER", "Engineer",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Engineer_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Engineer_Body.kv6", {0.0F, 0.0F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Engineer_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Engineer_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_Engineer_Arms_Upper.kv6", "kv6/Character_Engineer_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_12_group_0}, std::span<const std::uint16_t>{class_12_group_1}, std::span<const std::uint16_t>{class_12_group_2}, std::span<const std::uint16_t>{class_12_group_3}, std::span<const std::uint16_t>{class_12_group_4}, std::span<const std::uint16_t>{class_12_group_5}, std::span<const std::uint16_t>{class_12_group_6}},
        2000U, 3000U,
        {"png/ui/in_game_menus/select_class/engineer_character_team1.png", "png/ui/in_game_menus/select_class/engineer_character_team2.png"},
        {"png/ui/in_game_menus/select_class/engineer_icon_team1.png", "png/ui/in_game_menus/select_class/engineer_icon_team2.png"}, "", 1.1765},
    ClassDefinition{
        13U, "UGCBUILDER", "UGC Builder",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_UGCBuilder_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_UGCBuilder_Body.kv6", {0.0F, 0.0F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_UGCBuilder_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_UGCBuilder_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_UGCBuilder_Arms_Upper.kv6", "kv6/Character_UGCBuilder_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_13_group_0}, std::span<const std::uint16_t>{class_13_group_1}, std::span<const std::uint16_t>{class_13_group_2}, std::span<const std::uint16_t>{class_13_group_3}, std::span<const std::uint16_t>{class_13_group_4}, std::span<const std::uint16_t>{class_13_group_5}, std::span<const std::uint16_t>{class_13_group_6}},
        1U, 1U,
        {"png/ui/in_game_menus/select_class/ugcbuilder_character_team1.png", "png/ui/in_game_menus/select_class/ugcbuilder_character_team2.png"},
        {"png/ui/in_game_menus/select_class/ugcbuilder_icon_team1.png", "png/ui/in_game_menus/select_class/ugcbuilder_icon_team2.png"}, "", 0.0},
    ClassDefinition{
        14U, "FAST_ZOMBIE", "Fast Zombie",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Zombie_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Zombie_Body.kv6", {0.0F, 0.0F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, 0.0F, 0.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Zombie_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Zombie_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"", ""},
        {std::span<const std::uint16_t>{class_14_group_0}, std::span<const std::uint16_t>{class_14_group_1}, std::span<const std::uint16_t>{class_14_group_2}, std::span<const std::uint16_t>{class_14_group_3}, std::span<const std::uint16_t>{class_14_group_4}, std::span<const std::uint16_t>{class_14_group_5}, std::span<const std::uint16_t>{class_14_group_6}},
        500U, 1000U,
        {"png/ui/in_game_menus/select_class/zombie_character_team1.png", "png/ui/in_game_menus/select_class/zombie_character_team2.png"},
        {"png/ui/in_game_menus/select_class/zombie_icon.png", "png/ui/in_game_menus/select_class/zombie_icon.png"}, "", 0.5},
    ClassDefinition{
        15U, "JUMP_ZOMBIE", "Jump Zombie",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Zombie_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Zombie_Body.kv6", {0.0F, 0.0F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, 0.0F, 0.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Zombie_Leg.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Zombie_Leg.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"", ""},
        {std::span<const std::uint16_t>{class_15_group_0}, std::span<const std::uint16_t>{class_15_group_1}, std::span<const std::uint16_t>{class_15_group_2}, std::span<const std::uint16_t>{class_15_group_3}, std::span<const std::uint16_t>{class_15_group_4}, std::span<const std::uint16_t>{class_15_group_5}, std::span<const std::uint16_t>{class_15_group_6}},
        500U, 1000U,
        {"png/ui/in_game_menus/select_class/zombie_character_team1.png", "png/ui/in_game_menus/select_class/zombie_character_team2.png"},
        {"png/ui/in_game_menus/select_class/zombie_icon.png", "png/ui/in_game_menus/select_class/zombie_icon.png"}, "", 0.5},
    ClassDefinition{
        16U, "SPECIALIST", "Specialist",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Specialist_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Specialist_Body.kv6", {0.0F, 1.5F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Specialist_Leg_L.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Specialist_Leg_R.kv6", {0.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_Specialist_Arms_Upper.kv6", "kv6/Character_Specialist_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_16_group_0}, std::span<const std::uint16_t>{class_16_group_1}, std::span<const std::uint16_t>{class_16_group_2}, std::span<const std::uint16_t>{class_16_group_3}, std::span<const std::uint16_t>{class_16_group_4}, std::span<const std::uint16_t>{class_16_group_5}, std::span<const std::uint16_t>{class_16_group_6}},
        400U, 1000U,
        {"png/ui/in_game_menus/select_class/specialist_character_team1.png", "png/ui/in_game_menus/select_class/specialist_character_team2.png"},
        {"png/ui/in_game_menus/select_class/specialist_icon_team1.png", "png/ui/in_game_menus/select_class/specialist_icon_team2.png"}, "", 1.1765},
    ClassDefinition{
        17U, "MEDIC", "Medic",
        {{ClassBodyPartDefinition{BodyPart::head, "kv6/Character_Medic_Head.kv6", {0.0F, 0.0F, 5.5F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::torso, "kv6/Character_Medic_Body.kv6", {-1.0F, 1.5F, -9.0F}, {0.0F, 0.0F, 0.3F}},
         ClassBodyPartDefinition{BodyPart::arms_collision, "kv6/Character_Arms_Collision.kv6", {0.0F, -8.0F, -5.0F}, {0.0F, 0.0F, 0.5F}},
         ClassBodyPartDefinition{BodyPart::left_leg, "kv6/Character_Medic_Leg_L.kv6", {0.0F, 0.0F, -12.0F}, {0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::right_leg, "kv6/Character_Medic_Leg_R.kv6", {-2.0F, 0.0F, -12.0F}, {-0.25F, 0.0F, 1.1F}},
         ClassBodyPartDefinition{BodyPart::crouched_torso, "kv6/playertorsoc.kv6", {0.0F, 6.0F, -5.0F}, {0.0F, 0.0F, 0.0F}},
         ClassBodyPartDefinition{BodyPart::crouched_leg, "kv6/playerlegc.kv6", {0.0F, 0.0F, -5.0F}, {0.0F, 0.0F, 0.7F}}}},
        {"kv6/Character_Medic_Arms_Upper.kv6", "kv6/Character_Medic_Arms_Lower.kv6"},
        {std::span<const std::uint16_t>{class_17_group_0}, std::span<const std::uint16_t>{class_17_group_1}, std::span<const std::uint16_t>{class_17_group_2}, std::span<const std::uint16_t>{class_17_group_3}, std::span<const std::uint16_t>{class_17_group_4}, std::span<const std::uint16_t>{class_17_group_5}, std::span<const std::uint16_t>{class_17_group_6}},
        900U, 2000U,
        {"png/ui/in_game_menus/select_class/medic_character_team1.png", "png/ui/in_game_menus/select_class/medic_character_team2.png"},
        {"png/ui/in_game_menus/select_class/medic_icon_team1.png", "png/ui/in_game_menus/select_class/medic_icon_team2.png"}, "", 1.0},
}};

constexpr std::array<UiSkinDefinition, 2U> skins{{
    UiSkinDefinition{"default", ""},
    UiSkinDefinition{"mafia", "skins/mafia/"},
}};

} // namespace

std::span<const ClassDefinition> class_catalog() noexcept { return classes; }

const ClassDefinition* find_class_definition(std::uint8_t class_id) noexcept {
    return class_id < classes.size() ? &classes[class_id] : nullptr;
}

std::span<const UiSkinDefinition> ui_skin_catalog() noexcept { return skins; }

const UiSkinDefinition* find_ui_skin(std::string_view id) noexcept {
    const auto found = std::ranges::find_if(skins, [id](const auto& skin) { return skin.id == id; });
    return found == skins.end() ? nullptr : &*found;
}

std::vector<std::uint16_t> default_class_items(const ClassDefinition& definition, bool include_flare, bool include_prefab_tool) {
    std::vector<std::uint16_t> result;
    for (std::size_t group{}; group < static_cast<std::size_t>(ClassItemGroup::common); ++group) {
        if (group == static_cast<std::size_t>(ClassItemGroup::prefab_sets) || definition.item_groups[group].empty()) continue;
        result.push_back(definition.item_groups[group].front());
    }
    for (const auto item : definition.item_groups[static_cast<std::size_t>(ClassItemGroup::common)]) {
        if (item == 22U && !include_flare) continue;
        if (item == 23U && !include_prefab_tool) continue;
        if (item == 5U) result.insert(result.begin(), item); else result.push_back(item);
    }
    if (definition.class_id != 4U && definition.class_id != 5U && definition.class_id != 14U && definition.class_id != 15U) {
        if (include_flare && std::ranges::find(result, 22U) == result.end()) result.push_back(22U);
        if (include_prefab_tool && std::ranges::find(result, 23U) == result.end()) result.push_back(23U);
    }
    return result;
}

std::vector<std::uint8_t> class_test_tools(const ClassDefinition& definition) {
    std::vector<std::uint8_t> result;
    for (std::size_t group{}; group < definition.item_groups.size(); ++group) {
        if (group == static_cast<std::size_t>(ClassItemGroup::prefab_sets) || group == static_cast<std::size_t>(ClassItemGroup::ugc_tools)) continue;
        for (const auto item : definition.item_groups[group]) {
            if (item <= 64U && valid_selectable_tool(static_cast<std::uint8_t>(item)) && std::ranges::find(result, static_cast<std::uint8_t>(item)) == result.end()) result.push_back(static_cast<std::uint8_t>(item));
        }
    }
    return result;
}

std::optional<std::uint8_t> preferred_spawn_tool(const ClassDefinition& definition, std::span<const std::uint8_t> loadout) noexcept {
    const auto primary = definition.item_groups[static_cast<std::size_t>(ClassItemGroup::primary)];
    for (const auto choice : primary) {
        if (choice <= 64U && valid_selectable_tool(static_cast<std::uint8_t>(choice)) && std::ranges::find(loadout, static_cast<std::uint8_t>(choice)) != loadout.end()) return static_cast<std::uint8_t>(choice);
    }
    const auto fallback = std::ranges::find_if(loadout, [](std::uint8_t tool) { return valid_selectable_tool(tool); });
    return fallback == loadout.end() ? std::nullopt : std::optional<std::uint8_t>{*fallback};
}

std::string_view class_item_group_name(ClassItemGroup group) noexcept {
    constexpr std::array names{std::string_view{"Melee"}, std::string_view{"Primary"}, std::string_view{"Secondary"}, std::string_view{"Equipment"}, std::string_view{"Prefab sets"}, std::string_view{"Common"}, std::string_view{"UGC tools"}};
    const auto index = static_cast<std::size_t>(group); return index < names.size() ? names[index] : std::string_view{};
}

std::string_view class_catalog_contract_sha256() noexcept { return "698729231cc2464b7b94eb16d8555e9dee41229929ca39e74864e41c18adaae0"; }

} // namespace battlespades::world
