#include "battlespades/world/player_movement.hpp"

#include <algorithm>
#include <array>
#include <cmath>
#include <limits>

namespace battlespades::world {
namespace {

// Round only where the original x86 engine stored a float. Intermediate
// products remain double, matching the precision retained by x87.
[[nodiscard]] double f32(double value) noexcept {
    return static_cast<double>(static_cast<float>(value));
}

constexpr std::array<MovementClassConfig, 18U> class_movement_profiles{{
    {0.7, 1.4, 0.5, 1.2, 8, true, 10, 40, 100, 0.5},
    {0.7, 1.45, 0.5, 1.5, 8, true, 10, 30, 100, 0.5},
    {0.7, 1.1, 0.5, 1.0, 12.0, true, 10, 10, 10, 0.5},
    {0.7, 1.4, 0.5, 1.2, 8, true, 10, 40, 100, 0.5},
    {0.5, 1.65, 0.5, 1.5, 4.0, true, 10, 60, 100, 0.25},
    {1.0, 1.33, 0.5, 1.0, 8, false, 6, 26, 100, 1.0},
    {0.7, 1.5, 0.5, 1.2, 8, true, 10, 40, 100, 0.5},
    {0.7, 1.5, 0.5, 1.2, 8, true, 10, 40, 100, 0.5},
    {0.7, 1.5, 0.5, 1.2, 8, true, 10, 40, 100, 0.5},
    {0.7, 1.5, 0.5, 1.2, 8, true, 10, 40, 100, 0.5},
    {0.7, 1.5, 0.5, 1.2, 8, true, 10, 40, 100, 0.5},
    {0.7, 1.5, 0.5, 1.2, 8, true, 10, 40, 100, 0.5},
    {0.7, 1.25, 0.5, 1.0, 8, true, 10, 40, 100, 0.5},
    {1.0, 3.0, 0.5, 1.0, 1.0, true, 255, 255, 0, 1.0},
    {1.1, 3.0, 0.25, 2.5, 12.0, true, 6, 20, 500, 2.0},
    {0.5, 1.0, 0.5, 3.0, 8, false, 15, 25, 100, 0.5},
    {0.85, 1.55, 0.5, 1.5, 8, true, 10, 40, 100, 0.5},
    {0.6, 1.35, 0.5, 1.2, 8, true, 10, 40, 100, 0.5},
}};

// Original x86 world.pyd behavior, shared with the server and tested
// against fixtures generated by executing that unchanged binary.
constexpr double default_world_gravity{1.0};
constexpr double player_radius{0.45};
constexpr double standing_contact_offset{2.25};
constexpr double crouching_contact_offset{1.35};
constexpr double crouch_shift{0.9};
constexpr double fall_slow_down{0.24};
constexpr double ground_friction{4.0};
constexpr double air_friction{2.0};
constexpr double physics_scale{32.0};
constexpr double grounded_probe_epsilon{0.00875};
constexpr double map_edge{512.0};
constexpr double map_height{240.0};
[[nodiscard]] bool is_solid(const VxlMap* map, int x, int y, int z) noexcept {
    if (x < 0 || x >= static_cast<int>(map_edge) || y < 0 || y >= static_cast<int>(map_edge)) {
        return true;
    }
    if (z < 0 || z >= static_cast<int>(map_height) || map == nullptr) {
        return false;
    }
    return map->solid(static_cast<std::uint32_t>(x), static_cast<std::uint32_t>(y),
                      static_cast<std::uint32_t>(z));
}

/**
 * Retail clipbox @0x3c00 with allow_below_water=0. Truncation semantics at
 * block boundaries are load-bearing: a probe exactly on an integer face
 * belongs to the higher block, z in (-1,0) is empty, x/y outside the map
 * read solid, the open-water row 239 samples the bed at 238 and z>239 is
 * the solid world floor.
 */
[[nodiscard]] bool clip(const VxlMap* map, double x, double y, double z) noexcept {
    x = f32(x);
    y = f32(y);
    z = f32(z);
    if (x < 0.0) {
        return true;
    }
    const int ix = static_cast<int>(x);
    if (ix > 511) {
        return true;
    }
    if (y < 0.0) {
        return true;
    }
    const int iy = static_cast<int>(y);
    if (iy > 511) {
        return true;
    }
    const int iz = static_cast<int>(z);
    if (iz < 0) {
        return false;
    }
    int sample_z = 238;
    if (iz != 239) {
        sample_z = iz;
        if (iz > 238) {
            return true;
        }
    }
    if (map == nullptr) {
        return false;
    }
    return map->solid(static_cast<std::uint32_t>(ix), static_cast<std::uint32_t>(iy),
                      static_cast<std::uint32_t>(sample_z));
}

/** The four AABB corners at radius 0.45 — retail's only lateral probe set. */
[[nodiscard]] bool clip_corners(const VxlMap* map, double cx, double cy, double z) noexcept {
    cx = f32(cx);
    cy = f32(cy);
    z = f32(z);
    constexpr double radius{0.449999988079071};
    return clip(map, cx - radius, cy - radius, z) || clip(map, cx - radius, cy + radius, z) ||
           clip(map, cx + radius, cy - radius, z) || clip(map, cx + radius, cy + radius, z);
}

struct MoveBoxResult final {
    bool climbed{};
    bool landed{};
    bool airborne{};
    bool wade{};
    bool wade_valid{};
    bool crouch{};
};

/**
 * Single-pass port of the retail boxclipmove @0x3e90: X section, X glide,
 * Y section (with the X-glided z), Y glide, then the vertical move. All
 * intermediates are float32 like the compiled engine; double changes voxel
 * selection at exact contact planes and diverges collision branches.
 */
MoveBoxResult move_box(Vec3& position, Vec3& velocity, double dt, const VxlMap* map,
                       bool crouch, bool hover, bool sprint, bool can_uphill,
                       bool airborne, bool wade) {
    static_cast<void>(wade);
    const float px = static_cast<float>(position.x);
    const float py = static_cast<float>(position.y);
    const float pz = static_cast<float>(position.z);
    float vx = static_cast<float>(velocity.x);
    float vy = static_cast<float>(velocity.y);
    float vz = static_cast<float>(velocity.z);
    bool result_crouch = crouch;
    bool climbed = false;

    const float v35 = static_cast<float>(dt) * static_cast<float>(physics_scale);
    const float candidate_x = static_cast<float>(static_cast<double>(vx) * v35 + px);
    const float candidate_y = static_cast<float>(static_cast<double>(vy) * v35 + py);

    int lp{};
    float m{};
    float rad{};
    if (crouch && !hover) {
        lp = 2;
        m = 0.89999998F;
        rad = 0.44999999F;
    } else {
        lp = 3;
        m = 1.3499999F;
        rad = 0.89999998F;
    }
    const float v31 = rad;
    const float v36 = pz + rad;
    const float v40 = m + v36;
    float wx = px;
    float wy = py;

    // ---- X section ----
    {
        bool advanced = false;
        for (int level = 0; level < lp; ++level) {
            if (clip_corners(map, candidate_x, py, v40 - static_cast<float>(level))) {
                break;
            }
            if (level + 1 == lp) {
                wx = candidate_x;
                advanced = true;
            }
        }
        if (!advanced && !crouch && !hover && (!sprint || can_uphill)) {
            bool hit = false;
            for (int level = 0; level < lp; ++level) {
                if (clip_corners(map, candidate_x, py,
                                 (v40 - static_cast<float>(level)) - 1.0F)) {
                    vx = 0.0F;
                    hit = true;
                    break;
                }
            }
            if (!hit && !clip_corners(map, candidate_x, wy, (v36 - m) - 1.0F)) {
                wx = candidate_x;
                climbed = true;
            }
        }
    }

    // ---- X glide pass ----
    float glide = 0.0F;
    float glided_base = v36;
    {
        bool overlap = true;
        for (int level = 0; level < lp; ++level) {
            if (clip_corners(map, wx, wy, v40 - static_cast<float>(level))) {
                break;
            }
            if (level + 1 == lp) {
                overlap = false;
            }
        }
        if (overlap) {
            // The glide amount stays set even when the head revert fires:
            // retail still takes the frozen-z glide finalize that frame.
            glide = static_cast<float>((static_cast<double>(vx) * vx * 4.0 + static_cast<double>(0.05F)) * v35);
            const float head = std::floor(v36 - m);
            if (clip_corners(map, wx, wy, head)) {
                wx = px;
                vx = 0.0F;
            } else {
                glided_base = v36 - glide;
                vz = 0.0F;
            }
        }
    }
    float v37 = glided_base;
    const float v45 = m + glided_base;

    // ---- Y section (at the X-advanced x, with the glided z) ----
    {
        bool advanced = false;
        for (int level = 0; level < lp; ++level) {
            if (clip_corners(map, wx, candidate_y, v45 - static_cast<float>(level))) {
                break;
            }
            if (level + 1 == lp) {
                wy = candidate_y;
                advanced = true;
            }
        }
        if (!advanced && !crouch && !hover && (!sprint || can_uphill)) {
            bool hit = false;
            for (int level = 0; level < lp; ++level) {
                if (clip_corners(map, wx, candidate_y,
                                 (v45 - static_cast<float>(level)) - 1.0F)) {
                    vy = 0.0F;
                    hit = true;
                    break;
                }
            }
            if (!hit && !clip_corners(map, wx, candidate_y, (v37 - m) - 1.0F)) {
                wy = candidate_y;
                climbed = true;
            }
        }
    }

    // ---- Y glide pass ----
    {
        bool overlap = true;
        for (int level = 0; level < lp; ++level) {
            if (clip_corners(map, wx, wy, v45 - static_cast<float>(level))) {
                break;
            }
            if (level + 1 == lp) {
                overlap = false;
            }
        }
        if (overlap) {
            const float lift = static_cast<float>((static_cast<double>(vy) * vy * 4.0 + static_cast<double>(0.05F)) * v35);
            glide = lift;
            const float head = std::floor(v37 - m);
            if (clip_corners(map, wx, wy, head)) {
                wy = py;
                vy = 0.0F;
            } else {
                v37 = v37 - lift;
                vz = 0.0F;
            }
        }
    }

    // ---- finalize ----
    position.x = wx;
    position.y = wy;
    MoveBoxResult result;
    result.crouch = result_crouch;
    if (climbed) {
        velocity.x = vx;
        velocity.y = vy;
        velocity.z = vz;
        position.z = v37 - v31;
        result.climbed = true;
        result.airborne = false;
        return result;
    }
    if (glide != 0.0F) {
        // Glide frame: the vertical move is skipped entirely (z frozen at
        // the glided value, airborne untouched). Auto-crouch into a
        // one-and-a-fraction block gap.
        if (!result_crouch) {
            if (clip(map, wx, wy, std::floor(m + v37)) &&
                !clip(map, wx, wy, std::floor(v37)) &&
                !clip(map, wx, wy, std::floor(v37 - m))) {
                result.crouch = true;
            }
        }
        velocity.x = vx;
        velocity.y = vy;
        velocity.z = vz;
        position.z = v37 - v31;
        result.airborne = airborne;
        return result;
    }

    // Normal vertical move.
    const float direction = vz >= 0.0F ? m : -m;
    v37 = static_cast<float>(v37 + static_cast<double>(v35) * vz);
    const float probe = std::floor(direction + v37);
    if (!clip_corners(map, wx, wy, probe)) {
        velocity.x = vx;
        velocity.y = vy;
        velocity.z = vz;
        position.z = v37 - v31;
        result.airborne = true;
        return result;
    }
    // Vertical blocked: keep the exact frame-start z (no partial advance).
    position.z = pz;
    velocity.x = vx;
    velocity.y = vy;
    velocity.z = 0.0;
    if (vz >= 0.0F) {
        result.landed = true;
        result.airborne = false;
        result.wade = pz > 237.0F;
        result.wade_valid = true;
        return result;
    }
    result.airborne = true;
    return result;
}

/**
 * Port of check_for_ground_holes @0x2290: standing still on a ledge lip
 * (own column empty one block under the feet) drifts the player toward the
 * hole centre so client and server settle identically.
 */
void check_for_ground_holes(Vec3& position, Vec3& velocity, double dt, const VxlMap* map,
                            bool crouch, bool hover, const PlayerInputState& input) {
    const double feet =
        f32(f32(position.z) + (crouch && !hover ? 1.3499999 : 2.25));
    if (input.forward || input.backward || input.left || input.right) {
        return;
    }
    const int column_x = static_cast<int>(std::floor(position.x));
    const int column_y = static_cast<int>(std::floor(position.y));
    const int below = static_cast<int>(std::floor(f32(feet + 1.0)));
    if (!(below > 239 || below < 0 || column_y > 511 || column_y < 0 || column_x > 511 ||
          !is_solid(map, column_x, column_y, below))) {
        return;
    }

    const double to_center_x = f32((static_cast<double>(column_x) + 0.5) - f32(position.x));
    const double abs_x = std::fabs(to_center_x);
    const int neighbor_x = abs_x != 0.0
                               ? column_x - static_cast<int>(to_center_x / abs_x)
                               : std::numeric_limits<int>::min() / 2;
    bool x_neighbor_empty = true;
    if (below >= 0 && below <= 239 && column_y >= 0 && column_y <= 511 && neighbor_x >= 0 &&
        neighbor_x <= 511) {
        x_neighbor_empty = !is_solid(map, neighbor_x, column_y, below);
    }

    const double to_center_y = f32((static_cast<double>(column_y) + 0.5) - f32(position.y));
    const double abs_y = std::fabs(to_center_y);
    const int neighbor_y = abs_y != 0.0
                               ? column_y - static_cast<int>(to_center_y / abs_y)
                               : std::numeric_limits<int>::min() / 2;
    bool y_neighbor_empty = true;
    if (below >= 0 && below <= 239 && neighbor_y >= 0 && neighbor_y <= 511 && column_x >= 0 &&
        column_x <= 511) {
        y_neighbor_empty = !is_solid(map, column_x, neighbor_y, below);
    }

    bool push_x = !x_neighbor_empty;
    bool push_y = !y_neighbor_empty;
    if (x_neighbor_empty && y_neighbor_empty && below >= 0 && below <= 239 &&
        neighbor_y >= 0 && neighbor_y <= 511 && neighbor_x >= 0 && neighbor_x <= 511 &&
        is_solid(map, neighbor_x, neighbor_y, below)) {
        // Both straight neighbours empty but the diagonal is solid: pick one
        // axis by signed dy <= dx.
        if (to_center_y <= to_center_x) {
            push_y = true;
        } else {
            push_x = true;
        }
    }

    if ((!push_x || abs_x <= static_cast<double>(0.2F)) && (!push_y || abs_y <= static_cast<double>(0.2F))) {
        if (push_x) {
            velocity.x = f32((to_center_x * dt) * 5.0);
        }
        if (push_y) {
            velocity.y = f32((to_center_y * dt) * 5.0);
        }
    }
}

// Original peer resolver captures its candidate once for the whole list.
std::size_t collide_with_players(PlayerMovementState& state,
                                std::span<const PlayerCollisionBody> bodies,
                                double dt, bool hover, bool resolve = true) noexcept {
    const double scale = f32(f32(dt) * physics_scale);
    const double own_height = f32((state.crouch && !hover ? 4.0 : 6.0) * 0.449999988079071);
    const double own_half = f32(own_height * 0.5);
    const double own_offset = f32(own_height - 0.449999988079071 - own_half);
    const Vec3 candidate{f32(f32(state.position.x) + f32(state.velocity.x) * scale),
                         f32(f32(state.position.y) + f32(state.velocity.y) * scale),
                         f32(f32(state.position.z) + f32(state.velocity.z) * scale + own_offset)};
    std::size_t collisions{};
    for (const auto& body : bodies) {
        if (!std::isfinite(body.position.x) || !std::isfinite(body.position.y) ||
            !std::isfinite(body.position.z) || !std::isfinite(body.height) || body.height <= 0.0)
            continue;
        const double other_height = f32(body.height);
        const double other_half = f32(other_height * 0.5);
        const double other_z = f32(body.position.z + f32(other_height - 0.449999988079071 - other_half));
        const double dx = f32(candidate.x - f32(body.position.x));
        const double dy = f32(candidate.y - f32(body.position.y));
        const double length = f32(std::sqrt(f32(dx * dx + dy * dy)));
        const double push = f32(std::max(0.0, 0.8999999761581421 - length));
        if (push <= 0.0) continue;
        const double dz = f32(candidate.z - other_z);
        const double overlap = f32(std::max(0.0, other_half + own_half - std::abs(dz)));
        if (overlap <= 0.0) continue;
        if (!resolve) { ++collisions; continue; }
        if (scale <= 0.0) continue;
        if (overlap > push) {
            const double strength = f32(push / scale);
            double nx{1.0}, ny{};
            if (dx != 0.0 && dy != 0.0) {
                const double inverse = f32(1.0 / length);
                nx = f32(dx * inverse);
                ny = f32(dy * inverse);
            }
            state.velocity.x = f32(f32(state.velocity.x) + f32(nx * strength));
            state.velocity.y = f32(f32(state.velocity.y) + f32(ny * strength));
        } else {
            const double strength = f32(overlap / scale);
            const double nz = dz == 0.0 ? 1.0 : f32(dz * f32(1.0 / f32(std::sqrt(f32(dz * dz)))));
            state.velocity.z = f32(f32(state.velocity.z) + f32(nz * strength));
            if (dz < 0.0) state.fall_distance = 0.0;
        }
        ++collisions;
    }
    return collisions;
}

} // namespace

bool constrain_player_to_bounds(PlayerMovementState& state,
                                const PlayerMovementBounds& bounds) noexcept {
    const auto finite = [](Vec3 value) {
        return std::isfinite(value.x) && std::isfinite(value.y) &&
               std::isfinite(value.z);
    };
    if (!finite(state.position) || !finite(state.velocity) ||
        !finite(bounds.minimum) || !finite(bounds.maximum) ||
        bounds.minimum.x > bounds.maximum.x ||
        bounds.minimum.y > bounds.maximum.y ||
        bounds.minimum.z > bounds.maximum.z) {
        return false;
    }
    const auto constrain_axis = [](double& position,
                                   double& velocity,
                                   double minimum,
                                   double maximum) {
        if (position < minimum) {
            position = minimum;
            if (velocity < 0.0)
                velocity = 0.0;
        } else if (position > maximum) {
            position = maximum;
            if (velocity > 0.0)
                velocity = 0.0;
        }
    };
    constrain_axis(state.position.x, state.velocity.x,
                   bounds.minimum.x, bounds.maximum.x);
    constrain_axis(state.position.y, state.velocity.y,
                   bounds.minimum.y, bounds.maximum.y);
    constrain_axis(state.position.z, state.velocity.z,
                   bounds.minimum.z, bounds.maximum.z);
    return true;
}

MovementClassConfig movement_config_for_class(
    std::uint8_t class_id, double movement_speed_scale) noexcept {
    auto result = class_id < class_movement_profiles.size()
                      ? class_movement_profiles[class_id]
                      : class_movement_profiles[0U];
    if (!std::isfinite(movement_speed_scale) || movement_speed_scale <= 0.0) {
        movement_speed_scale = 1.0;
    }
    result.accel_multiplier *= movement_speed_scale;
    result.sprint_multiplier *= movement_speed_scale;
    result.crouch_sneak_multiplier *= movement_speed_scale;
    return result;
}

double player_contact_offset(bool crouch, bool wade) noexcept {
    return crouch && !wade ? crouching_contact_offset : standing_contact_offset;
}

double player_body_height(bool crouch, bool wade) noexcept {
    return player_contact_offset(crouch, wade) + player_radius;
}

bool clip_at(const VxlMap* map, double x, double y, double z) noexcept {
    return clip(map, x, y, z);
}

bool grounded(const VxlMap* map, const PlayerMovementState& state) noexcept {
    const double feet =
        state.position.z + player_contact_offset(state.crouch, state.wade);
    const int sample_z = static_cast<int>(std::floor(feet + grounded_probe_epsilon));
    const int west = static_cast<int>(std::floor(state.position.x - player_radius));
    const int east = static_cast<int>(std::floor(state.position.x + player_radius));
    const int north = static_cast<int>(std::floor(state.position.y - player_radius));
    const int south = static_cast<int>(std::floor(state.position.y + player_radius));
    for (const int bx : {west, east}) {
        for (const int by : {north, south}) {
            if (is_solid(map, bx, by, sample_z)) {
                return true;
            }
        }
    }
    return feet >= map_height;
}

void apply_crouch_request(PlayerMovementState& state, bool crouch, const VxlMap* map,
                         std::span<const PlayerCollisionBody> bodies, bool hover) {
    bool target = crouch;
    if (hover) { state.crouch = crouch; target = false; }
    if (target == state.crouch) return;
    if (target) {
        if (!state.airborne) state.position.z = f32(f32(state.position.z) + crouch_shift);
        state.crouch = true;
        return;
    }
    const double old_z = f32(state.position.z);
    const double lower_probe = f32(old_z + 2.25);
    const double upper_probe = f32(old_z - 1.350000023841858);
    state.crouch = false;
    bool can_stand = state.airborne &&
        !clip_corners(map, state.position.x, state.position.y, lower_probe) &&
        collide_with_players(state, bodies, 0.0, hover, false) == 0U;
    if (!can_stand) {
        state.position.z = f32(old_z - static_cast<double>(0.9F));
        can_stand = !clip_corners(map, state.position.x, state.position.y, upper_probe) &&
                    collide_with_players(state, bodies, 0.0, hover, false) == 0U;
        if (!can_stand) state.position.z = f32(f32(state.position.z) + static_cast<double>(0.9F));
    }
    state.crouch = hover || !can_stand;
}

MovementStepResult step_player(PlayerMovementState& state, const PlayerInputState& input,
                               const VxlMap* map, double dt,
                               const MovementClassConfig& movement_class,
                               std::span<const PlayerCollisionBody> collision_bodies,
                               double world_gravity) {
    dt = f32(dt);
    const double gravity = f32(std::isfinite(world_gravity) && world_gravity > 0.0 &&
                                   world_gravity <= 8.0 ? world_gravity : default_world_gravity);
    MovementStepResult result;
    const bool hover = input.hover && state.jetpack == 4U;
    const bool valid_pack = state.jetpack >= 1U && state.jetpack <= 4U;
    result.jumped = input.jump && !state.airborne;
    if (input.jump) {
        if (state.jetpack_active && valid_pack) {
            constexpr std::array<float, 4U> thrust{0.045F, 0.0125F, 0.020F, 0.025F};
            state.velocity.z = f32(f32(state.velocity.z) -
                ((gravity + 1.0) * static_cast<double>(thrust[state.jetpack - 1U])) * 0.5);
            state.fall_distance = 0.0;
        } else if (!state.jetpack_active && !state.airborne) {
            state.velocity.z = f32(static_cast<double>(-0.36F) * f32(movement_class.jump_multiplier));
        }
    } else if (hover) {
        state.velocity.z = state.crouch
            ? f32(f32(state.velocity.z) - ((gravity + 1.0) * static_cast<double>(-0.025F)) * 0.5)
            : 0.0;
    }
    double accel = f32((state.crouch && !hover) || input.sneak
        ? movement_class.crouch_sneak_multiplier
        : (input.sprint && !state.burdened ? movement_class.sprint_multiplier : movement_class.accel_multiplier));
    accel = f32(accel * dt);
    if (state.airborne) {
        if (state.jetpack_active && !hover && (state.jetpack == 3U || state.jetpack == 4U))
            accel = f32(accel * static_cast<double>(0.1F));
        else if (!state.jetpack_active || hover || state.jetpack == 1U || state.jetpack == 2U)
            accel = f32(accel * 0.5);
    }
    if ((input.forward || input.backward) && (input.left || input.right))
        accel = f32(accel * static_cast<double>(0.7071067690849304F));

    // Forward normalization rounds length squared, sqrt, inverse and products
    // separately. Side direction mirrors the server orientation setter.
    double ox = f32(state.orientation.x), oy = f32(state.orientation.y);
    const double length_squared = f32(ox * ox + oy * oy);
    if (length_squared > 0.0) {
        const double inverse = f32(1.0 / f32(std::sqrt(length_squared)));
        ox = f32(ox * inverse);
        oy = f32(oy * inverse);
    }
    const double side_length = std::sqrt(state.orientation.x * state.orientation.x + state.orientation.y * state.orientation.y);
    const double sx = side_length > 0.0 ? f32(-state.orientation.y / side_length) : 0.0;
    const double sy = side_length > 0.0 ? f32(state.orientation.x / side_length) : 1.0;
    if (input.forward) {
        state.velocity.x = f32(f32(state.velocity.x) + ox * accel);
        state.velocity.y = f32(f32(state.velocity.y) + oy * accel);
    }
    if (input.backward) {
        state.velocity.x = f32(f32(state.velocity.x) - ox * accel);
        state.velocity.y = f32(f32(state.velocity.y) - oy * accel);
    }
    if (input.left) {
        state.velocity.x = f32(f32(state.velocity.x) - sx * accel);
        state.velocity.y = f32(f32(state.velocity.y) - sy * accel);
    }
    if (input.right) {
        state.velocity.x = f32(f32(state.velocity.x) + sx * accel);
        state.velocity.y = f32(f32(state.velocity.y) + sy * accel);
    }
    if (state.climb_timer > 0.0) {
        state.velocity.x = f32(f32(state.velocity.x) * f32(state.climb_slowdown));
        state.velocity.y = f32(f32(state.velocity.y) * f32(state.climb_slowdown));
    }
    const double divisor = f32(dt + 1.0);
    double gravity_step = dt * gravity;
    if (state.jetpack_passive) gravity_step *= 0.75;
    else if (state.parachute_active) gravity_step *= static_cast<double>(0.05F);
    if (!hover && (!state.jetpack_passive || valid_pack))
        state.velocity.z = f32(f32(state.velocity.z) + gravity_step);
    state.velocity.z = f32(f32(state.velocity.z) / divisor);
    if (state.parachute_active) state.fall_distance = 0.0;
    const double horizontal_divisor = state.airborne && (state.jetpack_active || state.jetpack_passive)
        ? divisor : f32(dt * (state.wade ? f32(movement_class.water_friction)
            : (state.airborne ? air_friction : ground_friction)) + 1.0);
    state.velocity.x = f32(f32(state.velocity.x) / horizontal_divisor);
    state.velocity.y = f32(f32(state.velocity.y) / horizontal_divisor);
    const double landing_speed = f32(state.velocity.z);
    static_cast<void>(collide_with_players(state, collision_bodies, dt, hover));
    double move_start_z = state.position.z;
    const auto moved = move_box(state.position, state.velocity, dt, map, state.crouch,
                                hover, input.sprint, movement_class.can_sprint_uphill,
                                state.airborne, state.wade);
    if (moved.crouch && !state.crouch) move_start_z = f32(f32(move_start_z) + static_cast<double>(0.9F));
    state.crouch = moved.crouch;
    result.climbed = moved.climbed;
    result.landed = moved.landed;
    const double fall_delta = f32(state.position.z - move_start_z);
    if (fall_delta > 0.0) state.fall_distance = f32(f32(state.fall_distance) + fall_delta);
    else if (fall_delta < -0.1) state.fall_distance = 0.0;
    if (moved.climbed) state.climb_timer = static_cast<double>(0.1F);
    state.climb_timer = std::max(0.0, f32(f32(state.climb_timer) - dt));
    state.airborne = moved.airborne;
    if (moved.wade_valid) state.wade = moved.wade;
    if (state.position.z > map_height) state.position.z = 238.0;
    if (state.velocity.z == 0.0) {
        check_for_ground_holes(state.position, state.velocity, dt, map, state.crouch, hover, input);
        double fall = f32(f32(state.fall_distance) * gravity);
        if (state.jetpack_passive && valid_pack) fall = f32(fall * 0.75);
        const double minimum = f32(movement_class.falling_damage_min_distance);
        const double maximum = f32(movement_class.falling_damage_max_distance);
        const double span = f32(maximum - minimum);
        double ratio = f32(span > 0.0 ? f32(fall - minimum) / span : (fall >= maximum ? 1.0 : 0.0));
        ratio = std::clamp(ratio, 0.0, 1.0);
        auto damage = static_cast<int>(f32(f32(movement_class.falling_damage_max_damage) * ratio));
        if (state.position.z > 237.0)
            damage = static_cast<int>(damage * f32(movement_class.fall_on_water_damage_multiplier));
        state.fall_distance = 0.0;
        result.landing_damage = damage;
        if (landing_speed > fall_slow_down) {
            result.hard_landing = true;
            if (landing_speed > f32(static_cast<double>(0.8F) / gravity)) {
                state.velocity.x *= 0.5;
                state.velocity.y *= 0.5;
            }
            if (damage == 0) result.landing_damage = -1;
        }
    }
    return result;
}

} // namespace battlespades::world
