// Generated by tools/generate-achievement-table.py from
// config/achievements/retail-achievements.tsv. Do not edit by hand.

#include "battlespades/frontend/achievements.hpp"

#include <array>

namespace battlespades::frontend {
namespace {

constexpr std::array<AchievementDefinition, 77U> definitions{{
    {"airborne_for_hour", "NEW_ACHIEVEMENT_4_19", "Time Flies", "Spend a total of an hour in the air", "airborne_seconds_count", 3600U},
    {"airborne_rockets", "NEW_ACHIEVEMENT_4_5", "Sky rockets in flight", "Score 5 direct hits with rockets while airborne", "airborne_rocket_count", 5U},
    {"ammo_drop_greedy", "NEW_ACHIEVEMENT_3_14", "Loaded", "Collect a full resupply of ammunition in one game", "", 0U},
    {"blocks_as_zombie", "NEW_ACHIEVEMENT_4_14", "Dead Can Dig", "Destroy 666 blocks as a zombie", "block_as_zombie_count", 666U},
    {"bomb_final_bomber", "NEW_ACHIEVEMENT_2_21", "Bomb the Base", "Be the final player to plant a bomb successfully, and then win the round.", "", 0U},
    {"bomb_hotfoot", "NEW_ACHIEVEMENT_2_19", "Hotfoot", "Pick up a bomb from a spawn point and make it to the enemy base without dropping it", "", 0U},
    {"bomb_interceptor", "NEW_ACHIEVEMENT_2_20", "Bomb Disposal Expert", "Intercept 5 bomb carriers and defend the bomb until it detonates early.", "bomb_interceptor_count", 5U},
    {"bomb_survivor", "NEW_ACHIEVEMENT_2_18", "Bombs Away!", "Drop a bomb in the enemy base and survive", "", 0U},
    {"classic_kills_with_intel", "NEW_ACHIEVEMENT_4_22", "Courier Killer", "Kill 5 players while carrying the intel in classic", "classic_kills_with_intel_count", 5U},
    {"classic_rifle_headshots", "NEW_ACHIEVEMENT_4_4", "Open Your Mind", "Score 50 headshots with the classic rifle", "classic_rifle_headshot_count", 50U},
    {"demolition_damage_many_rounds", "NEW_ACHIEVEMENT_2_24", "Attack the Blocks", "Cause 500 blocks of damage to the enemy base over multiple rounds", "demolition_damage_many_rounds_count", 500U},
    {"demolition_damage_one_round", "NEW_ACHIEVEMENT_2_23", "Block Party", "Cause 100 blocks of damage to the enemy base in one round", "", 0U},
    {"demolition_final_damage", "NEW_ACHIEVEMENT_2_25", "Put the Boot in", "Be the final player to cause damage to the enemy base and win", "", 0U},
    {"demolition_repair", "NEW_ACHIEVEMENT_2_22", "Fort Process", "Repair 100 blocks of damage to your base", "demolition_repair_count", 100U},
    {"diamond_collector", "NEW_ACHIEVEMENT_2_8", "Girl's Best Friend", "Find and drop off 3 diamonds in one match", "", 0U},
    {"diamond_hotfoot", "NEW_ACHIEVEMENT_2_7", "Diamond Geezer", "Pick up a diamond within 5 seconds of it spawning, and make it to a dropoff point without dropping it", "", 0U},
    {"diamond_interceptor", "NEW_ACHIEVEMENT_2_10", "King of Diamonds", "Intercept 10 diamonds carried by the enemy team and make it to a dropoff point", "diamond_interceptor_count", 10U},
    {"diamond_thief", "NEW_ACHIEVEMENT_2_9", "Feeling Flush", "Steal and drop off 5 diamonds found by the enemy team before they pick them up", "diamond_thief_count", 5U},
    {"drillgun_demolition", "NEW_ACHIEVEMENT_3_9", "All Your Base", "Destroy 1000 blocks of enemy bases in demolition mode using the drill gun", "drillgun_demolition_count", 1000U},
    {"dynamite_below", "NEW_ACHIEVEMENT_3_10", "Floored Genius", "Kill 10 enemies by placing dynamite below them then blowing out the floor", "dynamite_below_count", 10U},
    {"grenade_demolish", "NEW_ACHIEVEMENT_2_29", "Holey Hand Grenade", "Demolish 5 structures of 100 or more blocks using a grenade", "grenade_demolish_count", 5U},
    {"health_drop_greedy", "NEW_ACHIEVEMENT_3_15", "Well Heeled", "Repair 150 health in one game using health drops", "", 0U},
    {"hill_defender", "NEW_ACHIEVEMENT_2_15", "Tor Defence", "Retain control of 10 contested hills", "hill_defender_count", 10U},
    {"hill_greedy", "NEW_ACHIEVEMENT_2_11", "One Man Army", "Be the only player to score points from a hill before it vanishes", "", 0U},
    {"hill_interceptor", "NEW_ACHIEVEMENT_2_14", "Cubic Heir", "Take control of 10 contested hills", "hill_interceptor_count", 10U},
    {"hill_kill_shooting_in", "NEW_ACHIEVEMENT_2_17", "Butte Hurt", "Take out 50 enemy players while they are in an active hill", "hill_kill_shooting_in_count", 50U},
    {"hill_kill_shooting_out", "NEW_ACHIEVEMENT_2_16", "Mountain Casualties", "Take out 50 enemy players while you are in an active hill", "hill_kill_shooting_out_count", 50U},
    {"hill_strike_stay_put", "NEW_ACHIEVEMENT_2_13", "Strikebreaker", "Trigger an airstrike and survive without leaving the hill", "", 0U},
    {"hill_strike_survivor", "NEW_ACHIEVEMENT_2_12", "Shock and Awe", "Trigger 5 airstrikes and survive", "hill_strike_survivor_count", 5U},
    {"intel_defence_easy", "NEW_ACHIEVEMENT_4_2", "Stop, thief!", "Intercept 5 enemies stealing your intel and defend it until it returns to base.", "intel_defence_count", 5U},
    {"intel_defence_hard", "NEW_ACHIEVEMENT_4_3", "Undelivered Message Report", "Intercept 10 enemies stealing your intel and defend it until it returns to base.", "intel_defence_count", 10U},
    {"jetpack_kill", "NEW_ACHIEVEMENT_3_3", "Rocket Man", "Kill 20 enemies while using the jetpack", "jetpack_kill_count", 20U},
    {"jetpack_killed_using", "NEW_ACHIEVEMENT_3_5", "Jet Fighter", "Kill an enemy while he uses a jetpack", "", 0U},
    {"jetpack_smg_kill", "NEW_ACHIEVEMENT_3_6", "Jetpack Drive-by", "Kill 10 enemies with the SMG while using the jetpack", "jetpack_smg_kill_count", 10U},
    {"knife_zombies", "NEW_ACHIEVEMENT_4_6", "Bit Late for an Autopsy", "Knife 10 zombies", "knife_zombie_count", 10U},
    {"landmine_hidden", "NEW_ACHIEVEMENT_3_1", "Landmine Craft", "Kill 5 players with landmines placed on the ground and re-buried", "landmine_hidden_count", 5U},
    {"lastman_kills_zombies_easy", "NEW_ACHIEVEMENT_4_11", "Groovy!", "As last man standing take out at least 5 zombies in one round", "", 0U},
    {"lastman_kills_zombies_hard", "NEW_ACHIEVEMENT_4_12", "Come get some!", "As last man standing take out at least 10 zombies in one round", "", 0U},
    {"low_health_killing", "NEW_ACHIEVEMENT_4_10", "Riskbreaker", "Kill ten players when your health is below 10% over multiple rounds", "low_health_kills", 10U},
    {"map_colosseum_kill", "NEW_ACHIEVEMENT_3_24", "The Undertaker", "Kill 10 enemies while hiding in the tunnel under the arena", "", 0U},
    {"map_concrete_destroy", "NEW_ACHIEVEMENT_3_21", "Pillar Assault", "In demolition mode, destroy all the pillars in the enemy building lobby", "", 0U},
    {"map_egypt_destroy", "NEW_ACHIEVEMENT_3_23", "Nose Job", "Destroy the nose of the Sphinx", "", 0U},
    {"map_greatwall_destroy", "NEW_ACHIEVEMENT_3_16", "The War on Terracotta", "Destroy the Terracotta Army", "", 0U},
    {"map_isleofdoom_destroy", "NEW_ACHIEVEMENT_4_1", "Exit The Dragon", "Dragon Island: Destroy the stone dragon", "", 0U},
    {"map_london_destroy", "NEW_ACHIEVEMENT_3_19", "Death Toll", "Destroy the large bell at the top of Big Ben", "", 0U},
    {"map_maya_kill", "NEW_ACHIEVEMENT_3_20", "Personal Sacrifice", "Melee kill an enemy while standing near the temple altar", "", 0U},
    {"map_moon_destroy", "NEW_ACHIEVEMENT_3_18", "Kubrick Equation", "Lunar Base: Destroy the monolith with the rocket launcher", "", 0U},
    {"map_zombieisland_destroy", "NEW_ACHIEVEMENT_3_28", "Tower Offense", "Playing as a zombie, demolish the mansion's towers", "", 0U},
    {"map_zombieisland_zombie_kill", "NEW_ACHIEVEMENT_3_27", "Brain Drain", "Kill 5 zombies while hiding in the basement", "", 0U},
    {"minigun_demolish", "NEW_ACHIEVEMENT_2_26", "Riddle Me This", "Demolish a structure of 50 blocks or more using the minigun", "", 0U},
    {"misc_fifteen_in_a_row", "NEW_ACHIEVEMENT_4_8", "OMG Hax!", "Get fifteen kills in a row without dying", "", 0U},
    {"misc_five_in_a_row", "NEW_ACHIEVEMENT_3_31", "Five Alive", "Get five kills in a row without dying", "", 0U},
    {"misc_half_marathon", "NEW_ACHIEVEMENT_3_29", "Half Marathon", "Run 21 kilometers", "distance_run", 21000U},
    {"misc_marathon", "NEW_ACHIEVEMENT_3_30", "Marathon Man", "Run 42 kilometers", "distance_run", 42000U},
    {"misc_ten_in_a_row", "NEW_ACHIEVEMENT_4_7", "Streaker", "Get ten kills in a row without dying", "", 0U},
    {"misc_triple_explosion", "NEW_ACHIEVEMENT_4_0", "The Big Bang", "Kill 3 enemies with 1 explosion", "", 0U},
    {"pickaxe_kill", "NEW_ACHIEVEMENT_3_2", "Take Your Pick", "Kill 10 enemies with the pickaxe", "pickaxe_kill_count", 10U},
    {"pistol_zombie_kill", "NEW_ACHIEVEMENT_2_28", "Face Off", "Kill 5 zombies by shooting them in the face with the pistol", "pistol_zombie_kill_count", 5U},
    {"rocket_fall", "NEW_ACHIEVEMENT_2_27", "Splashback Cashback", "Make someone fall to their death using rocket launcher knockback", "", 0U},
    {"shotgun_headshots", "NEW_ACHIEVEMENT_3_7", "Heads You Win", "10 headshots with the shotgun", "shotgun_headshots_count", 10U},
    {"sniper2_rapid_kill", "NEW_ACHIEVEMENT_4_20", "The Quick and the Dead", "Kill 3 enemies in 20 seconds with the semi-auto sniper rifle", "", 0U},
    {"sniper_accuracy", "NEW_ACHIEVEMENT_2_31", "Hat Trick", "3 kills with sniper rifle without missing a shot", "", 0U},
    {"sniper_accuracy_hard", "NEW_ACHIEVEMENT_4_21", "Wisely Snipes", "6 kills with sniper rifle without missing a shot", "", 0U},
    {"sniper_kill", "NEW_ACHIEVEMENT_3_0", "Head Hunter", "25 headshots with the sniper rifle", "sniper_kill_count", 25U},
    {"sniper_kill_hard", "NEW_ACHIEVEMENT_4_9", "Hey, is that a sni-", "50 headshots with the sniper rifle", "sniper_kill_count", 50U},
    {"spade_kill", "NEW_ACHIEVEMENT_2_30", "Dig Deep", "Kill 10 enemies with the spade", "spade_kill_count", 10U},
    {"turret_accuracy", "NEW_ACHIEVEMENT_3_11", "Turret Syndrome", "Kill 10 enemies with 1 turret", "", 0U},
    {"turret_evasion", "NEW_ACHIEVEMENT_3_13", "Collateral Damage", "Destroy 100 blocks by evading an enemy turret", "", 0U},
    {"vip_mvp", "NEW_ACHIEVEMENT_2_5", "The Main Man", "Start the round as VIP and kill the highest number of enemy players", "", 0U},
    {"vip_pacifist", "NEW_ACHIEVEMENT_2_6", "I am the passenger", "Start the round as VIP, kill no enemy players, and survive anyway", "", 0U},
    {"zombie_fall", "NEW_ACHIEVEMENT_2_4", "Dead Drop", "Playing as a zombie, make an enemy player fall to their death", "", 0U},
    {"zombie_kills_humans", "NEW_ACHIEVEMENT_2_2", "Three of a Kind", "Take out 3 survivors in 1 round", "", 0U},
    {"zombie_kills_in_water_ach", "NEW_ACHIEVEMENT_4_13", "Water on the Brainnnns", "Kill 5 players as a zombie in the water", "zombie_kills_in_water", 5U},
    {"zombie_lms_multi_round", "NEW_ACHIEVEMENT_4_16", "Survivalist", "Survive as last man for 10 minutes total over multiple zombie rounds", "zombie_seconds_as_lms_count", 600U},
    {"zombie_lms_one_round", "NEW_ACHIEVEMENT_4_15", "28 Seconds Later", "Survive for 28 seconds as last man standing in one zombie round", "", 0U},
    {"zombie_mvp", "NEW_ACHIEVEMENT_2_3", "Stone Cold Killer", "Start the round as a zombie, and wipe out the highest number of enemy players", "", 0U},
    {"zombie_survivor", "NEW_ACHIEVEMENT_2_1", "Apocalypse Later", "Survive to the end of a round of Zombie", "", 0U},
}};

}  // namespace

std::span<const AchievementDefinition> retail_achievement_definitions() noexcept {
    return definitions;
}

}  // namespace battlespades::frontend
