#!/usr/bin/env python3
"""Regenerate the retail achievement table the client compiles in.

    python3 tools/generate-achievement-table.py

The source is config/achievements/retail-achievements.tsv: Steam's own schema
for application 224540 (API name, display name, description, backing stat and
threshold), read from the stats schema Steam caches for an installed game. The
server announces an unlock by display name (ACHIEVEMENT_GAINED), so the client
needs the names to recognise which achievement that was.
"""
from __future__ import annotations

import csv
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "config/achievements/retail-achievements.tsv"
OUTPUT = ROOT / "src/frontend/achievements.generated.cpp"


def literal(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    with SOURCE.open(encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle, delimiter="\t"))
    rows.sort(key=lambda row: row["api_name"])
    if len({row["api_name"] for row in rows}) != len(rows):
        raise SystemExit("duplicate achievement API names")
    lines = [
        "// Generated by tools/generate-achievement-table.py from",
        "// config/achievements/retail-achievements.tsv. Do not edit by hand.",
        "",
        '#include "battlespades/frontend/achievements.hpp"',
        "",
        "#include <array>",
        "",
        "namespace battlespades::frontend {",
        "namespace {",
        "",
        f"constexpr std::array<AchievementDefinition, {len(rows)}U> definitions{{{{",
    ]
    for row in rows:
        threshold = int(row["threshold"]) if row["threshold"] else 0
        lines.append(
            "    {"
            + ", ".join(
                (
                    literal(row["api_name"]),
                    literal(row["token"]),
                    literal(row["display_name"]),
                    literal(row["description"]),
                    literal(row["stat"]),
                    f"{threshold}U",
                )
            )
            + "},"
        )
    lines += [
        "}};",
        "",
        "}  // namespace",
        "",
        "std::span<const AchievementDefinition> retail_achievement_definitions() noexcept {",
        "    return definitions;",
        "}",
        "",
        "}  // namespace battlespades::frontend",
        "",
    ]
    OUTPUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {len(rows)} achievements to {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
