#!/usr/bin/env python3
"""Generate the native F12 parity-browser inventory from the RE JSON catalog."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any


NATIVE_FIXTURES = {
    "select_menu",
    "join_match",
    "server_browser",
    "public_match",
    "custom_match_list",
    "create_match_lobby",
    "create_match_lobby.settings",
    "create_match_lobby.rules",
    "create_match_lobby.playlists",
    "create_match_lobby.maps",
    "ugc_select",
    "ugc_editor_lobbies",
    "ugc_editor_lobby",
    "ugc_publish",
    "player_profile",
    "leaderboard",
    "settings",
    "settings.main",
    "settings.graphics",
    "settings.controls",
    "loading",
    "change_resolution",
}


def literal(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def string_list(values: list[str]) -> str:
    return "{" + ", ".join(literal(value) for value in values) + "}"


def source_location(record: dict[str, Any]) -> str:
    source = str(record.get("source", ""))
    line = record.get("line")
    return f"{source}:{line}" if line else source


def screen_entry(record: dict[str, Any]) -> dict[str, Any]:
    reachability = str(record.get("reachability", "reachable"))
    kind = "component" if reachability in {"component", "abstract-screen"} else "screen"
    controls = []
    for control in record.get("controls", []):
        name = str(control.get("id", control.get("type", "control")))
        control_type = str(control.get("type", "Control"))
        label = str(control.get("labelKey", ""))
        controls.append(f"{name} : {control_type}" + (f" [{label}]" if label else ""))
    states = [str(value) for value in record.get("states", [])]
    states.extend(str(value) for value in record.get("subviews", []))
    return {
        "id": str(record["id"]),
        "class": str(record.get("class", record["id"])),
        "kind": kind,
        "route": str(record.get("route", "")),
        "parent": str(record.get("parentScreen", "")),
        "source": source_location(record),
        "widgets": controls,
        "assets": [str(value) for value in record.get("assets", [])],
        "states": states,
        "native": str(record["id"]) in NATIVE_FIXTURES,
    }


def auxiliary_entry(record: dict[str, Any], group: str) -> dict[str, Any]:
    class_name = str(record.get("class", record.get("name", "Unknown")))
    source_kind = str(record.get("kind", ""))
    if group in {"widgetTypes", "listRowTypes", "navigationFactories"}:
        kind = "widget"
    elif source_kind in {"service", "data", "helper"}:
        kind = "service"
    else:
        kind = "component"
    detail = []
    if record.get("base"):
        detail.append(f"base : {record['base']}")
    if record.get("role"):
        detail.append(str(record["role"]))
    return {
        "id": f"{group}.{class_name}",
        "class": class_name,
        "kind": kind,
        "route": "",
        "parent": "",
        "source": source_location(record),
        "widgets": detail,
        "assets": [],
        "states": [],
        "native": False,
    }


def generate(catalog: dict[str, Any], source_sha256: str) -> str:
    entries = [screen_entry(record) for record in catalog["screens"]]
    represented_classes = {entry["class"] for entry in entries}
    for group in ("frontendClasses", "widgetTypes", "navigationFactories", "listRowTypes"):
        for record in catalog.get(group, []):
            class_name = str(record.get("class", record.get("name", "Unknown")))
            if group == "frontendClasses" and class_name in represented_classes:
                continue
            entries.append(auxiliary_entry(record, group))

    entries.append(
        {
            "id": "fixture.frontend_shell_transition",
            "class": "MenuScene transition fixture",
            "kind": "component",
            "route": "",
            "parent": "",
            "source": "aoslib/scenes/frontend/menuScene.py:49",
            "widgets": ["forward slide", "back slide", "halfway input gate"],
            "assets": [],
            "states": ["current_x=+1", "current_x=-1", "accept input below abs(0.5)"],
            "native": False,
        }
    )
    entries.append(
        {
            "id": "fixture.retail_cursor",
            "class": "ImageMouseCursor",
            "kind": "widget",
            "route": "",
            "parent": "",
            "source": "aoslib/run.py:396",
            "widgets": ["64x64 image", "hotspot (6, 60) in pyglet coordinates"],
            "assets": ["png/ui/cursor.png"],
            "states": ["installed globally"],
            "native": False,
        }
    )

    lines = [
        "// Generated by tools/generate-retail-ui-catalog.py. Do not hand edit.",
        f"// Source SHA-256: {source_sha256}",
        '#include "battlespades/frontend/parity_debug_menu.hpp"',
        "",
        "#include <vector>",
        "",
        "namespace battlespades::frontend {",
        "namespace {",
        "const std::vector<ParityCatalogEntry> catalog{",
    ]
    for entry in entries:
        lines.extend(
            [
                "    ParityCatalogEntry{",
                f"        {literal(entry['id'])},",
                f"        {literal(entry['class'])},",
                f"        ParityCatalogKind::{entry['kind']},",
                f"        {literal(entry['route'])},",
                f"        {literal(entry['parent'])},",
                f"        {literal(entry['source'])},",
                f"        {string_list(entry['widgets'])},",
                f"        {string_list(entry['assets'])},",
                f"        {string_list(entry['states'])},",
                f"        {'true' if entry['native'] else 'false'},",
                "    },",
            ]
        )
    lines.extend(
        [
            "};",
            "} // namespace",
            "",
            "std::span<const ParityCatalogEntry> retail_frontend_catalog() noexcept {",
            "    return catalog;",
            "}",
            "",
            "} // namespace battlespades::frontend",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    source = args.input.read_bytes()
    catalog = json.loads(source.decode("utf-8"))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        generate(catalog, hashlib.sha256(source).hexdigest().upper()),
        encoding="utf-8",
        newline="\n",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
