#!/usr/bin/env python3
"""Regenerate the retail Steam achievement catalogue.

Ace of Spades' achievements are defined on Steam application 224540, which this
project does not own, so their API names cannot be invented: Steam refuses a
name its schema does not know. They are public, though. The global achievement
percentages endpoint lists every one of them without a publisher key, and that
list is the authority this catalogue copies.

    python3 tools/generate-steam-achievements.py

The percentages themselves move as people play and are deliberately not stored.
What an achievement *requires* is not published anywhere, so the catalogue
carries names only; a name is wired to a gameplay event by hand, with evidence,
never by guessing from the name.
"""
from __future__ import annotations

import json
import pathlib
import sys
import urllib.request

APP_ID = 224540
ENDPOINT = (
    "https://api.steampowered.com/ISteamUserStats/"
    f"GetGlobalAchievementPercentagesForApp/v2/?gameid={APP_ID}"
)
OUTPUT = (
    pathlib.Path(__file__).resolve().parent.parent
    / "include/battlespades/platform/steam_achievements.generated.hpp"
)


def fetch_names() -> list[str]:
    with urllib.request.urlopen(ENDPOINT, timeout=30) as response:
        payload = json.load(response)
    achievements = payload["achievementpercentages"]["achievements"]
    names = sorted({str(entry["name"]) for entry in achievements})
    if not names:
        raise SystemExit("Steam returned no achievements for this application")
    for name in names:
        if not name.replace("_", "").isalnum():
            raise SystemExit(f"unexpected achievement name from Steam: {name!r}")
    return names


def render(names: list[str]) -> str:
    lines = [
        "#pragma once",
        "",
        "// Generated by tools/generate-steam-achievements.py. Do not edit.",
        "//",
        "// The retail achievement names defined on Steam application "
        f"{APP_ID}.",
        "// Steam refuses a name its schema does not know, so these are copied",
        "// from the application's public achievement list rather than invented.",
        "",
        "#include <array>",
        "#include <string_view>",
        "",
        "namespace battlespades::platform {",
        "",
        f"/** Every achievement the retail application defines ({len(names)}). */",
        f"inline constexpr std::array<std::string_view, {len(names)}> "
        "retail_achievements{",
    ]
    lines += [f'    "{name}",' for name in names]
    lines += [
        "};",
        "",
        "/** True when Steam's schema for the retail application defines this name. */",
        "[[nodiscard]] inline constexpr bool is_retail_achievement("
        "std::string_view name) noexcept {",
        "    for (const auto candidate : retail_achievements) {",
        "        if (candidate == name) return true;",
        "    }",
        "    return false;",
        "}",
        "",
        "} // namespace battlespades::platform",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    names = fetch_names()
    OUTPUT.write_text(render(names), encoding="utf-8")
    print(f"wrote {len(names)} achievement names to {OUTPUT.relative_to(OUTPUT.parents[3])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
